### ISSUE TITLE
Detection potion is unbrewable due to it conflicting with vanilla night vision recipe

### ISSUE THREAD

**Issue by tiggerbiggo** [zabi94/ExtraAlchemy#101]
No need for version information, the problem is evident in the code on the current 1.16 branch:

`registerPotion(ModConfig.INSTANCE.potions.detection, ModPotionRegistry.detection, Items.GOLDEN_CARROT, Potions.AWKWARD);`

The vanilla night vision potion already uses awkward potion and golden carrots resulting in REI showing no recipe for the  detection potion, and a night vision potion to be brewed when this combination of ingredients is mixed.

Please can you choose a different item which will fix this issue or make it use a different base potion.

Thanks

**Comment by zabi94** [comment]
Yes, it is a known bug. I'll find the time to fix it soon

**Comment by tiggerbiggo** [comment]
If you let me know what item or base potion you want me to change it to i can fix it and make a Pull request, but it's your call. Thanks for the mod i just tried the detection effect and it's awesome :)

**Comment by zabi94** [comment]
Don't worry, I should have a few free hours tomorrow, I'll fix it
