### ISSUE TITLE
Potion of Detection is Uncraftable

### ISSUE THREAD

**Issue by The13thEmpire** [zabi94/ExtraAlchemy#103]
The Potion of detection and Potion of Night Vision have the same recipe. (Awkward potion + Golden Carrot)

Mod Version: 1.4.3
Game Version: 1.16.5
This is seen in my modpack:
Modpack: Origins Initium 
Version: 1.1.0

**Comment by zabi94** [comment]
Duplicate of #101, fixed in version 1.4.4.
Ask the pack maker to update
