### ISSUE TITLE
Can't mix potions

### ISSUE THREAD

**Issue by Wallano-pand** [zabi94/ExtraAlchemy#107]
**Describe the bug**
Even if i put some potions with a slime ball in the center that are identical, i can't mix them

**To Reproduce**
1. Go to a crafting table and put a slime in the center with identical potions

**Expected behavior**
I should get a potion with increased duration
**Screenshots**
![image](https://user-images.githubusercontent.com/83022365/115734869-69136a00-a360-11eb-9fca-bcc91f0c4745.png)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: https://pastebin.com/5TPyTxqQ
 - Mod List: 
 - Extra Alchemy Config: https://pastebin.com/ixjVesxq

**Environment (please complete the following information):**
 - Mod Version: [1.4.4]
 - MC Version: [1.16.5]
 - Fabric Version: [idk]
 - Fabric API version: [0.33.0]
 - System: [Windows 10] 
 - Installation type: [Lan]

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
As described in the [mod's page](https://minecraft.curseforge.com/projects/extra-alchemy), the feature has not been ported to 1.14+ yet

**Comment by Wallano-pand** [comment]
oh sorry, i didnt saw

**Comment by zabi94** [comment]
Don't worry, it happens. It's the next feature I'll port
