### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Snoe0** [zabi94/ExtraAlchemy#108]
This is only occurring for one of my friends, and not the rest, but his game crashes with this error.

![image](https://user-images.githubusercontent.com/83789327/119196307-f3301a80-ba53-11eb-92ea-36ba61aad8f2.png)

Using Fabric API 0.34.21.16

Mods List:

Appleskins
Optifabric
Optifine
Voicechat
Fabric API
ModMenu-Use latest version if it doesn’t works, usually fixes it
Roughly Enough Items
Wraith Waystones
Improved Stations
Go Fish
Traverse
Croptopia
Fabric Language Kotin
Better Caves
Linked Storage
Blockus
Diggus Maximus
Vanilla Hammers
Sandwichable
Yung Api
Pehkui
Hwyla
Terrestria
Origins
Deep Dungeons
Environmental Armor
Extra Alchemy
All Stackable
Impersonate
Undefeatables
Tech Reborn
Reborn Core
Lifts
FOF
Geckolib
Applied Energistics2
Adorn
Cosmetic Armor Rework
Origin Classes
Mob Origins

**Comment by zabi94** [comment]
Please follow the crash report template, I need those information to fix it
