### ISSUE TITLE
Add Hoppers/Iron Blocks as a conductor

### ISSUE THREAD

**Issue by Wdavery** [zabi94/ExtraAlchemy#109]
Hoppers can be used to help automate the brewing stand, which limits you from using a heat source. I think hoppers would act as a conductor of a heat source below quite well (being iron). Iron blocks would be a great conductor as well.

**Comment by zabi94** [comment]
Makes sense. For the time being you can use a datapack to define them as heat conductor on your worlds, there won't be any update for a few weeks still
