### ISSUE TITLE
[1.10.2] Potion of Detection Not Highlighting Entities

### ISSUE THREAD

**Issue by Gelles** [zabi94/ExtraAlchemy#11]
#### Type of Issue (Bug / Crash / Suggestion / Translation / ...):
Potion of Detection does not work (no entities are highlighted).
---

#### Version of the mod or build number:
Version 0.3.04-hotfix release

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2...):
1.10.2 w/ Forge 12.18.3.2185 (Recommended version)
---

#### Description of the issue (or what were you doing when it crashed):
No crash occurs and no errors appear in the log. For testing, I tried both giving myself a potion from the creative inventory and brewing a potion manually. Neither worked.
---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
https://pastebin.com/L8Pucx5L
---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
No modpack; tested with only Extra Alchemy and Forge.

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
https://pastebin.com/PmwmxPct

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
Java 8/Windows 10

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
Judging by the log I assume you are playing in a single player world, am I correct?

**Comment by Gelles** [comment]
Yes, single-player only.
