### ISSUE TITLE
Potion Rings don't work in Inventorio's additional slots

### ISSUE THREAD

**Issue by JumperREDACTED** [zabi94/ExtraAlchemy#110]
**Describe the bug**
Potion Ring's don't activate if placed into Inventorio's additional slots. (Either slots gained from the deep pocket enchantment, or the additional offhand slots.)
https://github.com/Lizard-Of-Oz/Inventorio/issues/31

**Pastebin links**
 - latest.log: was too long for pastebin
[latest.log](https://github.com/zabi94/ExtraAlchemy/files/6656215/latest.log)

**Environment (please complete the following information):**
 - Mod Version: 1.4.5
 - MC Version: 1.16.5
 - Fabric Version: 0.11.3
 - Fabric API version: 0.34.6
 - System: W10
 - Installation type: either

**Comment by zabi94** [comment]
Potion rings only work in ticking slots, inventorio must implement item ticking in its logic to be compatible

**Comment by zabi94** [comment]
Problem is, inventory ticking is not as straightforward to add as one might think. Many mods would probably crash or work weirdly, because they must be supplied with the inventory slot, but there is no way of telling the item what inventory to look in.

As a result, telling the item it is in slot 1 might cause the item's mod to look into the vanilla inventory slot 1, belonging to another item

**Comment by Lizard-Of-Oz** [comment]
Inventorio author here.
I'll implement an API for custom Inventorio ticking in a day or two (and some extra functionality for that matter).
It won't make things magically work with all mods, but will allow other mods to call Inventorio's item ticking, like with Trinkets or Curios.

**Comment by zabi94** [comment]
Works for me. I'll subscribe to the issue on your side to be notified when it closes, I'll close this one

**Comment by zabi94** [comment]
Implemented in 1.17 alpha build.
I couldn't do 1.16.4 because of a temporary problem (terraformersMC maven repo being down, used for many dependencies in ea), but I hope they will fix it by next week
