### ISSUE TITLE
magnetism potion crash

### ISSUE THREAD

**Issue by bovigit** [zabi94/ExtraAlchemy#111]
#### Please install [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) to allow me to read the stack trace

**To Reproduce**
Steps to reproduce the crash:
1. drink potion of magnetism, any of the three (default, plus time and magnetism II)
2. Absorb any item that's on the floor
3. Instant crash, also game crashes as soon as accessing the world where this crash happened.

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Crash Log: https://pastebin.com/UuMk6puR
 - Mod List:  included in pastebin above
 - Extra Alchemy Config: https://pastebin.com/RVTTWtm5

**Environment (please complete the following information):**
 - Mod Version: 1.5.0
 - MC Version: 1.17
 - Fabric Version: 0.11.6
 - Fabric API version: 0.36.0
 - System: windows 10, specifics also included in crash log pastebin
 - Installation type: single player

**Additional context**
some potions present no effects, like the piper potion, this was all tested in a creative mode world separate from my main one (thank god lol)  to test stuff, magnetism potion also had no effect, and when trying to absorb items in the default range game crashes instantly, and keeps crashing as soon as i rejoin world. hopefully i made no mistakes, first time presenting a crash/bug like this. thank you for your work!

**Comment by zabi94** [comment]
> hopefully i made no mistakes, first time presenting a crash/bug like this. thank you for your work!

This was \*chef's kiss\*
I wish all reports looked like yours!

**Comment by zabi94** [comment]
I'll address the piper potion issue in the next few days since it doesn't crash

**Comment by zabi94** [comment]
Actually, it was pretty easy. Still, I'll release the fix in a future update, since I just released the fix for the magnetism one on Curseforge, and I don't want to flood the page
