### ISSUE TITLE
Server Connection Issue: java.lang.IllegalArgumentException: Unknown recipe serializer extraalchemy:potion_ring

### ISSUE THREAD

**Issue by 0xmycf** [zabi94/ExtraAlchemy#113]
We setup a mc server with fabric and some mods. One of which is this.
It works with 4 out of 5 people, however with the last person we/he gets the following error shortly after connecting:
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer extraalchemy:potion_ring.`

I don't know how relevant this is: In his first attempt to join he put the mods folder I provided for him as .zip inside the mods folder, but we changed this after his first attempt and the directory is definitely correct now.

**What happened/how to reproduce**
1. Install the newest build from CurseForge of extraalchemy
2. Start MC
3. Connect to a server that has extraalchemy installed.
4. -> crash

**What should happen**
1. Install the newest build from CurseForge of extraalchemy
2. Start MC
3. Connect to a server that has extraalchemy installed.
4. -> connect

**Mod List:**
https://pastebin.com/pZ1y5RaL

 - Mod Version: extraalchemy-fabric-1.17-1.5.1
 - MC Version: 1.17.1
 - Fabric Version: Newest Version
 - Fabric API version: Pastebin
 - System: Windows 10
 - Installation type: DedicatedServer

**Additional context**
See beginning.

**Comment by zabi94** [comment]
Sounds like he has a mismatched version of the mod. Let's check the extra alchemy version he has installed: attach an in-game screenshot of the mod menu page or his latest.log file please

**Comment by 0xmycf** [comment]
Thank you for your quick response. 
We found the issue... Im a bit embarrassed that I have written this bug ticket...

Solution:
He didn't start MC with fabric and therefore no mods were loaded. I figured that after he said he had no Map (which he should have had)

Thank you!

**Comment by zabi94** [comment]
Np
