### ISSUE TITLE
"Lol no GTFO" Potion effect, under the name "Focus"

### ISSUE THREAD

**Issue by CubieJudy** [zabi94/ExtraAlchemy#114]
**Describe the bug**
While attempting numerous different potion effects (Learning, Scorching, Crumbling, and more) I would receive an odd potion effect called "Focus" with the Potion Icon being "LOL NO GTFO" (See image)

The odd thing is that this doesn't occur in a singleplayer world, only a multiplayer server im hosting.

**To Reproduce**
1. Host a 1.16.5 Fabric Server
2. Join and attempt to use the potions
3. See bug

**Expected behavior**
The potion effect I wanted.

**Screenshots**
![2021-07-23_01 39 27](https://user-images.githubusercontent.com/37309250/126743713-82cce408-668a-41d3-84bc-e6355b8351e4.png)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Mod List: https://pastebin.com/TgJSHMWk
 - Extra Alchemy Config: https://pastebin.com/8mgF4M4a

**Environment (please complete the following information):**
 - Mod Version: 1.4.5
 - MC Version: 1.16.5
 - Fabric Version: 0.7.4
 - Fabric API version: Fabric API 0.37.0
 - System: Windows 10
 - Installation type: Dedicated Server.

**Additional context**
This also seems to extend to the Netherite Plus mod, as that mod's Lava Vision is broken by this weird bug. but it doesn't break it in Single Player

**Comment by zabi94** [comment]
That's weird. That icon is what I jokingly use for instant potions, and should never be applied as a timed status effect.

How are you getting the effect on the player? By drinking or by command?

**Comment by CubieJudy** [comment]
I am drinking/breaking the potions, specifically the ones NOT instant.

As for the Lava Vision from the other mod, it's being given via a Netherite Beacon.

**Comment by zabi94** [comment]
No, the "instant" potion is not something you choose to use or not.

Every potion is either timed or instant. Let's take vanilla potions as an example: strength is a timed potion. It has a duration, and the effect stays on for a few minutes. Harming, on the other side, is instant. You drink the potion and you take damage, that's it, no effect is displayed in your inventory and it has no duration.

Focus is supposed to be like harming. It shouldn't have a duration at all. When I drink the potion in my game, I don't get any timed effect, it just applies the effect and then it's done.

I suspect something is changing how potions work and it is bugged. Would you mind sharing a screenshot of the tooltip of the potion you drink, while you have extended tooltips enabled? (F3+H)

**Comment by CubieJudy** [comment]
I feel there is a slight miscommunication as to the actual bug going on, so I have also provided a video to better demonstrate the issue i am running into!

![2021-07-24_02 13 23](https://user-images.githubusercontent.com/37309250/126859388-0e620a93-7401-46cf-a227-99bbab2ec4c6.png)

https://user-images.githubusercontent.com/37309250/126859425-83b3527a-2f44-4dc9-b9f4-42e0868baf45.mp4

**Comment by zabi94** [comment]
OOOOOH yeah, i definitely misunderstood what you meant.
That is concerning, I've never seen it happen before

**Comment by CubieJudy** [comment]
The really odd thing, which i feel may be important to reiterate, is that this only occurs on my multiplayer server, which has no mods that my client doesn't also have.

Here's a video just to demonstrate as a fact that they work just fine in Singleplayer

(Edit: skip to 37 seconds in, to skip the loading)
https://user-images.githubusercontent.com/37309250/126859734-1b282e80-14a9-4416-b887-862fda10ee37.mp4

**Comment by zabi94** [comment]
So, the bug doesn't happen in my environment, which makes me thing it is one of the other mods messing with potion code.
Is this a public modpack so that I don't have to download every single mod? If not, can you please zip your mods and config folder and send them over to me? It would save me a lot of time

**Comment by CubieJudy** [comment]
Absolutely!

It won't let me send it through Github, so this link should get you the file! If not, please let me know, and i can set up a google drive download for you!

Edit: You may notice that the "Spawner mod" mentioned in my Pastebin is no longer there. Earlier today i realized it was a Forge mod, and not a fabric mod, and so i removed it (didn't affect anything for the record)

https://cdn.discordapp.com/attachments/700480493128253560/868396831472754698/ForZabi.zip

**Comment by zabi94** [comment]
Hm, I just opened a server with your same mods and everything works. 
I assume it's something related to your origins mod/plugins at this point. 
What origin did you choose? Is the problem still present if you start a new game with a different origin?

**Comment by CubieJudy** [comment]
I set up a new world and everything ended up working fine even when I swapped to my Origin of choice... very bizarre.

It seems to just be that particular world... 

Does the mod change something within the world data that would cause the world to freak out?

**Comment by zabi94** [comment]
Nope. Very weird

**Comment by CubieJudy** [comment]
I was able to fix this issue by moving all of the world's files into a different folder, then rerouting the server to load that world folder rather then the old one.

I could not tell you WHY that fixes it, but everything works now!

Thanks for trying to help tho! :D
