### ISSUE TITLE
ability to change what the growth potions do

### ISSUE THREAD

**Issue by EmoBubbleGum** [zabi94/ExtraAlchemy#116]
these potions are really fun, but the effects are overkill. i'd like to get the best of both worlds, and have a way to config the insane amount of reach these potions give players.

**Comment by zabi94** [comment]
What would you want to change? The size?

**Comment by EmoBubbleGum** [comment]
size and speed for shrink/grow would be great too, but i was mainly thinking about that reach, grow lets you attack and break blocks 30+ blocks away atm. i'd personally only like it to extend reach by a few blocks, but that's my preference. seems like something that would be good to be adjustable.

**Comment by zabi94** [comment]
I use Pehkui's general reaizing. The default values are dictated by the library, I only decide a generic muliplicator and everything grows according to its rules.

I could tune them one by one, but the amount of work is just not worth it for the moment.
I'll leave this issue open, to let other people give their input on the matter, and consider it if it becomes a shared opinion

**Comment by EmoBubbleGum** [comment]
ahhh so at least for now i can bandaid fix most of the issues by editing the pehkui config. i appreciate this information

**Comment by zabi94** [comment]
I wasn't even aware the library allowed that config

**Comment by EmoBubbleGum** [comment]
it does, but i am really not sure how to edit these values, lol. 
![image](https://user-images.githubusercontent.com/24841270/132361268-a29c27b0-953d-47f5-80fa-c3ae0070aa8f.png)
changing the max to 1.7028234663852886E38 didnt seem to do much.

**Comment by EmoBubbleGum** [comment]
![image](https://user-images.githubusercontent.com/24841270/132363603-0ad412e6-2391-4324-9179-334e84c9f155.png)
tried completely disabling scaledreach and scaledattack, it had no effect.

**Comment by EmoBubbleGum** [comment]
so as a quick update, it's the same issue with the commands that change size. so it's not an issue with your mod. it's either pehkui, or this modpack... annoying

**Comment by EmoBubbleGum** [comment]
![javaw_HWyUvOoyQ6](https://user-images.githubusercontent.com/24841270/132373261-eea94f40-f7fe-4ce9-93d9-504a9b3f9c0b.png)
last update for now, a picture to emphasize the reach being large gives you for attacks (see the tree in the distance). i made a github issue with pehkui, hopefully gives some answers. though, it might be a good idea to change this for your mod by default, as it pretty badly breaks growth II potions, to be able to melee from 40 meters away

**Comment by zabi94** [comment]
Any news from pehkui side? Is this issue still relevant?

**Comment by EmoBubbleGum** [comment]
well, the scale change doesn't let you break blocks across the map anymore, but it's still really overkill, and disabling reach scaling in pehkui does nothing.
