### ISSUE TITLE
Certain potion recipes do not show their recipes in REI.

### ISSUE THREAD

**Issue by Neatro** [zabi94/ExtraAlchemy#117]
**Describe the bug**
Certain potion recipes (such as Gravity potion) do not show their recipes in Roughly Enough Items. Breakable potions do not show their recipes at all, only to craft the vial itself.

**To Reproduce**
Open inventory and search for this mod's potions (and breakable potions), then click on them to view the recipe, for some potions this recipe does not show.

**Expected behavior**
View the potion recipes

**Screenshots**
-

**Pastebin links**
ModList: https://pastebin.com/JJyDFgWZ

**Environment (please complete the following information):**
 - Mod Version: 1.6.1
 - MC Version: 1.17.1
 - Fabric Version: 0.11.6
 - Fabric API version: fabric-api-0.37.2
 - System: Windows 7
 - Installation type: Single player

**Additional context**
-

**Comment by zabi94** [comment]
is this a downloadable modpack or a collection of mods you chose?
If it is a modpack, can you please link it? It would make my life easier

**Comment by Neatro** [comment]
This is a custom collection of mods that i chose

**Comment by zabi94** [comment]
I'd kindly ask you to zip your mods folder and send it to me then. It would take me too much time to download them all

**Comment by Neatro** [comment]
I have sent over the mods folder through Discord

**Comment by zabi94** [comment]
Is this still relevant?
