### ISSUE TITLE
Mixin conflict with Carpet mod

### ISSUE THREAD

**Issue by itsdinkd** [zabi94/ExtraAlchemy#119]
**Describe the bug**
Receive mixin error on server start

[04:53:35] [main/WARN]: Method overwrite conflict for setAmount in extraalchemy.access.json:AccessorExperienceOrbEntity, previously written by carpet.mixins.ExperienceOrbEntityMixin. Skipping method.

**To Reproduce**
1. Turn on server
2. Read logs

**Expected behavior**
Not having a Mixin Confliction. I am not aware if this breaks any functionality in Extra Alchemy or not.

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: https://pastebin.com/gGEhzHUN (line 531)
 - Mod List: https://pastebin.com/VqQe1hnL
 - Extra Alchemy Config: https://pastebin.com/Z0duYSXF

**Environment (please complete the following information):**
 - Mod Version: [e.g. 1.2.0] extraalchemy-fabric-1.17.1-1.6.1
 - MC Version: [e.g. 1.16.1] 1.17.1
 - Fabric Version: [e.g. 0.6.1.45] :shrug:
 - Fabric API version: [e.g. Fabric API 0.16.2 build 385] 0.40.1
 - System: [e.g. Windows 10, Mac OS Big Sur, Manjaro Linux] linux
 - Installation type: [e.g. SinglePlayer, DedicatedServer, Lan] DedicatedServer

**Additional context**
Carpet's ExperienceOrbEntity is used to (if i am right) clump XP orbs together into one.

**Comment by itsdinkd** [comment]
?

**Comment by zabi94** [comment]
I work a full time job, and I have family issues. Fixes are gonna take some time

**Comment by itsdinkd** [comment]
Nice! same. 2 kids, full time job, and I manage and actively update a large modpack including a discord server for it with 10 to 20 players asking for support every day.

I wrote the question mark because you asked for a full template and nothing was mentioned after doing so 9 days ago, obviously it was lost. not trying to rush you.

**Comment by red2blue** [comment]
manage*

**Comment by zabi94** [comment]
> Nice!

Not what I'd expect to hear when someone says they have family issues.

> same

I'm sorry you also have someone in your close family with severe health issues.

> 2 kids, full time job, and I manage and actively update a large modpack including a discord server for it with 10 to 20 players asking for support every day

> not trying to rush you

 you definitely are by these 2 statements alone.
