### ISSUE TITLE
[1.11] Relying on CompactLayer 0.2.7

### ISSUE THREAD

**Issue by xbony2** [zabi94/ExtraAlchemy#12]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue (Bug / Crash / Suggestion / Translation / ...):
>Bug

---

#### Version of the mod or build number:
>0.3.1.2

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2...):
>1.11.2

---

#### Description of the issue (or what were you doing when it crashed):
>This mods relies on CompactLayer version 0.2.7. However, the latest version of CompactLayer on CurseForge is 0.2.5. This is obviously problematic as I cannot play the mod.

---

(screw your other required stuff :P)

**Comment by zabi94** [comment]
I should probably move this to the description page, I'm gonna do that as soon as I can
Read the changelog of [this](https://minecraft.curseforge.com/projects/extra-alchemy/files/2412671) version for links

Closing
