### ISSUE TITLE
world not loading 

### ISSUE THREAD

**Issue by wojek1900** [zabi94/ExtraAlchemy#120]
**Describe the bug**
world not creating/loading on my modpack
**To Reproduce**
1.install all mods and try to create a world(I don't know if I can provide a download link due to copyright reasons)

**Expected behavior**
I just want to know why extraalchemy not work with my modpack
**Screenshots**
![Zrzut ekranu (609)](https://user-images.githubusercontent.com/56089314/137137729-1579fdef-2d62-40c5-abcf-7847b04f15b8.png)
log-modlist-config    https://pastebin.com/aTpQShtY
modlist line 4406
config line 4845
**Environment (please complete the following information):**
 - Mod Version: [1.6.1]
 - MC Version: [ 1.17.1]
 - Fabric Version: [ fabric installer 0.8.0  (0.11.7)]
 - Fabric API version: [0.40.6]
 - System: [ Windows 10] 
 - Installation type: [SinglePlayer,]

**Additional context**

**Comment by zabi94** [comment]
For anyone wondering. The culprit appears to be https://www.curseforge.com/minecraft/mc-mods/magick-potions-and-pearls, using the same names in some mixins. Since the mod is inspired by EA, I'm waiting on their response
