### ISSUE TITLE
Cannot Join Minecraft Server 1.16.5

### ISSUE THREAD

**Issue by HoneyBB** [zabi94/ExtraAlchemy#121]
**Describe the bug**
Whenever I try joining my friends Minecraft server that requires this mod to play. It says Im missing "extraalchemy:shrinking" and "extraalchemy:growing" I have tried literally every 1.16.5 version and some below and some into the 1.17 (which would only crash my game)

Any help please? Server is running on 1.16.5.

**Comment by zabi94** [comment]
I'm missing all the data I need to be able to help. Please open a new issue and fill the sections properly, not just the "describe the bug" one.
