### ISSUE TITLE
Datapack not works.

### ISSUE THREAD

**Issue by seriousfreezing** [zabi94/ExtraAlchemy#123]
**Describe the bug**
I copied the whole datapack structure into github itself and it didn't work.

**To Reproduce**
1. Go to folder "datapacks" on your map.
2. Paste the "ExtraAlchemy/src/main/resources/data/extraalchemy/recipes" inside the datapack folder.

**Expected behavior**
It was supposed to change the values of the potion rings, but even changing .json changes nothing.

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: /
 - Mod List: /
 - Extra Alchemy Config: https://pastebin.com/pm95356q

**Environment (please complete the following information):**
 - Mod Version: 1.4.5
 - MC Version: 1.16.5
 - Fabric Version: 0.12.5
 - Fabric API version: fabric-api-0.42.0+1.16
 - System: Windows 10
 - Installation type: Singleplayer

**Additional context**
idk.

**Comment by zabi94** [comment]
Are you placing the jsons in the folder or are you using an actual zip datapack?

**Comment by seriousfreezing** [comment]
Is in the folder.

**Comment by seriousfreezing** [comment]
![image](https://user-images.githubusercontent.com/66693072/143327323-aa81211d-8afd-4eb3-a543-d1c0f05f4f1d.png)

**Comment by zabi94** [comment]
Those need to go into an actual datapack.
There are plenty of tutorials online like [this one](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack)

**Comment by seriousfreezing** [comment]
![image](https://user-images.githubusercontent.com/66693072/143578627-83428157-8b22-40ce-ad38-d4a2af57da1c.png)
But, I've been to this link, I've been to datapack documentations.

I believe the actual structure is correct, I believe it is non-functional .jsons

**Comment by zabi94** [comment]
Is it a zip file then?

**Comment by seriousfreezing** [comment]
No.

**Comment by zabi94** [comment]
Are you capable of changing vanilla recipes without making it a zip?

**Comment by seriousfreezing** [comment]
Dude, understand there is no .zip or .rar or .7zip

In the datapack folder there are only folders and .jsons.

**Comment by zabi94** [comment]
I don't understand what the issue is then. You made something that's not supposed to work, and it's not working. 
I'm clearly missing something here

**Comment by seriousfreezing** [comment]
Well, do you want me to send the datapack in .zip for you to analyze?

**Comment by zabi94** [comment]
I feel like you don't understand what I'm saying, or I am not understanding the problem.

Here's what I understand: you put loose json files into the datapack folder and you're complaining they are not working.

I said that for any ring recipe json to work, they MUST be part of a **zip** datapack.

You said there were no zips, so I linked the guide on how to create one in a valid datapack format.

You said you read that but you _believe_ it is a json format issue. 

---

Send me the datapack, yes. I feel like it will be easier to understand for both

**Comment by seriousfreezing** [comment]
[ExtraAlchemy.zip](https://github.com/zabi94/ExtraAlchemy/files/7614449/ExtraAlchemy.zip)

Well, if the problem is just putting the base folder in .zip then I'll test it and see if it works.

**Comment by zabi94** [comment]
It's not just a zip. The link I posted earlier explains how to make a valid zip. You need to include other stuff.

I'll look at the zip sometime this week hopefully, I can't really do that sooner.
Please update this if you can get it to work without me

**Comment by seriousfreezing** [comment]
Okay.. sorry for this.

**Comment by zabi94** [comment]
No worries, it was just miscommunication.
