### ISSUE TITLE
Server not starting up // conflict between Extra alchemy + pehkui

### ISSUE THREAD

**Issue by Maccysundae** [zabi94/ExtraAlchemy#124]
#### Please install [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) to allow me to read the stack trace

**To Reproduce**
Steps to reproduce the crash:
This is a server not able to start
1. Go to 'server folder'
2. Click on 'start.bat'
3. Crash (server doesn't start

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Crash Log: https://pastebin.com/7xF0Sn5t
 - Mod List: https://pastebin.com/vgY3Z00t
 - Extra Alchemy Config: default 

**Environment (please complete the following information):**
 - Mod Version: 1.6.1
 - MC Version: 1.17.1
 - Fabric Version: 0.12.6 
 - Fabric API version: 0.43+1.17
 - System: win 10
 - Installation type: Dedicated server

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

Looking at the crash logs my-self it appears to be issue with extra alchemy + pehkui v3.0.0 ( https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3542832 ) not being compatible. As it says "due to issues provided by extra alchemy" I am posting the issue here. Please let me know if there's anything that can be done, or whether to need to choose between the 2 mods.
If you require any more information please let me know.

**Comment by zabi94** [comment]
It seems that the new pehkui version made breaking changes to its API.
Use an older version for now, if no other mod depends on it

**Comment by Maccysundae** [comment]
I went back to pehkui 2.6.0 (and the dependent to 1 version earlier) and it has launched the server, thanks for the help

**Comment by zabi94** [comment]
I'll fix this in the next release.
I hope to find some time this or next weekend
