### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by RotokEralil** [zabi94/ExtraAlchemy#129]
**Describe the bug**
<html>
<body>

[10:27:51] [ForkJoinPool-1-worker-4/WARN]: The mod "extraalchemy" contains invalid entries in its mod json:
--
- Invalid entry in person "contribution" at line 19 column 21

</body>
</html>

**To Reproduce**
run game, check log

**Expected behavior**

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: 
 - Modpack link (preferred) or Mod List:
 - Custom changes to modpack (if using a modpack):
 - Extra Alchemy Config:

**Environment (please complete the following information):**
 - Mod Version: [1.7.0]
 - MC Version: [1.18.1]

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
This should not cause any crash, am I correct?

**Comment by RotokEralil** [comment]
Correct; just a bug, dont think it is serious, but wanted to bring it to your attention :)
