### ISSUE TITLE
Potion Bag, Vials and Recipes Dont exist in-game

### ISSUE THREAD

**Issue by EquinoxEUW** [zabi94/ExtraAlchemy#133]
When I try and spawn or craft the Potion bag, ring, or any of the vials with potions in them or empty they dont. The recipes also dont appear in my REI. The items dont really seem to appear to be in my server either. Any fixes?

1. Go to commands or REI inventory
2. Type in the command to give the item / Look up the item in REI
3. Command displays an error message / recipe doesnt exist

**Expected behavior**
To receive the item and see its recipe in REI

**Screenshots**

![163665936-5e2aae87-5a01-4f51-a411-7fbfcf6423b4](https://user-images.githubusercontent.com/102207880/163665975-87029a8f-5c1f-4051-8598-0e5dfbc4139d.png)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: ?
 - https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack | The 1.18.1 Version
 - Added Mods: Minegate
 - Extra Alchemy Config: ?

**Environment (please complete the following information):**
 - Mod Version: Latest Version
 - MC Version: 1.18.1
 - Fabric Version: Latest 1.18.1 Version
 - System: Win10
 - Installation type: Apex Server Hosting 6GB

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.
I have a slight feeling Minegate might be causing issues.

**Comment by zabi94** [comment]
The modpack you linked is a forge pack. Extra Alchemy is a Fabric mod since minecraft 1.13

**Comment by OfficialDio** [comment]
No, I use a fabric version, if you look through youl find it

**Comment by EquinoxEUW** [comment]
Here's the correct link, please ask if there was an issue with what I put before shutting down the post https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric

I use the 1.18.1 Version of this modpack

**Comment by zabi94** [comment]
The issue doesn't shut down when closed, you can still comment and I can reopen it, as you can see. Don't worry about it.
Does the mod show up in modmenu?

**Comment by EquinoxEUW** [comment]
Ahh i see, sorry, Im not sure how the whole thing works, I was worried this was going to get ignored as I think your mod is awesome :) It does yeah!

**Comment by zabi94** [comment]
If you write, in creative, `/give extraalch` and press the tab button, does it autocomplete to something?

**Comment by EquinoxEUW** [comment]
It does yeah 
![image](https://user-images.githubusercontent.com/102207880/163721510-f5c64391-d33c-4abd-a403-e4eff8c93a7f.png)

**Comment by zabi94** [comment]
And it doesn't give you anything? If that's the case, I'm absolutely confused.

**Comment by EquinoxEUW** [comment]
Yeah it jsut ives an empty command, I am too.

**Comment by zabi94** [comment]
Does the issue disappear when you take out the minegate mod?

**Comment by EquinoxEUW** [comment]
No it doesnt seem like it

**Comment by EquinoxEUW** [comment]
Hmm okay so interestingly enough, It actually works in my singleplayer world. But on the server it doesnt

**Comment by zabi94** [comment]
Sounds like either the server hasn't loaded the mod properly, or the mod was not installed server side.
Download the mod on the server again, and make sure the server has the permissions to read it if you have a linux based server, then restart it.
Include the server log file too, please

**Comment by EquinoxEUW** [comment]
Alright will do, All the potion effects and such from the mod work and the potions as well, just the vials and bag, ring dont seem to work. How do I check if the server reads the mod?

**Comment by zabi94** [comment]
That might just be the client desyncing the effects, thinking the server knows about them.
The logs will tell

**Comment by EquinoxEUW** [comment]
Where do I get the logs?

**Comment by zabi94** [comment]
In the server folder, there should be a whole directory of them called logs. Inside you should find a file named latest.log

**Comment by OfficialDio** [comment]
Gotcha will post them

**Comment by EquinoxEUW** [comment]
[latest.log](https://github.com/zabi94/ExtraAlchemy/files/8502081/latest.log)


Sorry for the late response!

**Comment by zabi94** [comment]
No worries.
I can confirm the mod is not installed server side.
If the jar is in the mods folder it may be corrupted. Try redownloading and reinstalling it in that case

**Comment by EquinoxEUW** [comment]
I see let me have a look

**Comment by EquinoxEUW** [comment]
Omg..... I uploaded that one mod out of the mods folder.... I am so sorry

**Comment by zabi94** [comment]
No problem. Let me know if there are other issues

**Comment by EquinoxEUW** [comment]
Thank you so much for the help though! I must have uploaded it outside by accident

**Comment by EquinoxEUW** [comment]
Yes, it does
