### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Bernard-Borg** [zabi94/ExtraAlchemy#135]
**To Reproduce**
Steps to reproduce the crash:
1. Go into the server once
2. Leave the server
3. Rejoin the server
4. Crash

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Crash Log: https://pastebin.com/eCDGWwFL
 - Modpack link (preferred) or Mod List: https://pastebin.com/w1XJ8SbL
 - Custom changes to modpack (if using a modpack): None
 - Extra Alchemy Config: default

**Environment (please complete the following information):**
 - Mod Version: 1.8.1
 - MC Version: 1.18.2
 - Fabric Version: 0.11.0
 - Fabric API version: Fabric API 0.57.0
 - System: Windows 10
 - Installation type: Dedicated Server

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
A method that is never called on a normal fabric server is called on the server through polymer.
My mod relies on the method being client side even though it is not explicitly declared.

**Comment by Patbox** [comment]
Every vanilla method that can be called from a server should work on it. Polymer uses it to generate server accurate tooltips for items. Other mods wanting to display them (for example a chest shop with a hologram) would also call that method, causing issues
