### ISSUE TITLE
Potion rings affect experience in unexpected ways with Linear XP mod

### ISSUE THREAD

**Issue by floral-qua-floral** [zabi94/ExtraAlchemy#139]
**Describe the bug**
When the [Linear XP](https://www.curseforge.com/minecraft/mc-mods/linear-xp) mod is used alongside Extra Alchemy, potion rings' experience cost does not work as expected. The exact result seems to depend on how much experience the player already has; at some levels, the player will gain experience instead of using it, at other levels, the player will lose experience, and at others the rings will not drain any experience.

**To Reproduce**
1. Install Extra Alchemy with Linear XP
2. Enter a world and run `/xp set @s 1 levels`, then `/xp set @s 1 levels`
3. Obtain a potion ring; I used Ring of Speed I for this test
4. Activate the ring. The player will drop to about 75% of a level.
5. Cause the ring to trigger again by waiting until the effect times out, or removing it with milk or `/effect clear`.
6. The player will now have a little over 3 levels.
Step 5 can be repeated as many times as desired. When starting at 1 level with 0 points, using a Ring of Speed I, the player's level will eventually settle at a bit over 13, at which point the ring no longer affects experience at all.

**Expected behavior**
The player loses experience at a consistent rate. Since Linear XP makes every level worth the same amount of experience, the player should theoretically see the bar decreasing at a consistent speed regardless of level.

**Recording**
https://user-images.githubusercontent.com/49110090/187188973-47692018-72cb-4a13-bf4f-a3478ccad0a6.mp4

**Pastebin links**
 - latest.log: Nothing interesting going on in there, but for the sake of thoroughness, [here's the log.](https://mclo.gs/zB34cLy)
 - Modpack link (preferred) or Mod List: N/A, issue is reproducible with only Extra Alchemy, Linear XP, and Fabric API
 - Custom changes to modpack (if using a modpack): N/A
 - Extra Alchemy Config: Unmodified

**Environment (please complete the following information):**
 - Mod Version: Extra Alchemy 1.8.3
 - Linear XP version: 1.0.1
 - MC Version: 1.19
 - Fabric Version: 0.14.9
 - Fabric API version: 0.58.0
 - System: Windows 10
 - Installation type: Singleplayer

**Comment by zabi94** [comment]
This seems like an issue with the linear xp mod. I'm removing XP like everything else does.
The mod doesn't seem to be open source, there is no way I can try to understand how it affects minecraft.
