### ISSUE TITLE
Undeclared compatlayer dependency

### ISSUE THREAD

**Issue by Baughn** [zabi94/ExtraAlchemy#14]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
> Crash

---

#### Version of the mod or build number:
> 0.3.2-beta

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
> All of the above

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
> 1.10.2

---

#### Description (or what were you doing when it crashed):
> The Curseforge dependencies list for Extra Alchemy doesn't include CompatLayer, but the mod crashes if it isn't included. You need to add it as a required library.

**Comment by zabi94** [comment]
It is actually already dependent, not sure what you're talking about. Look
at the bottom of this page:

**Comment by zabi94** [comment]
![shot-20170528-5087-vrxn5p](https://cloud.githubusercontent.com/assets/11521878/26526463/4e08bc26-437c-11e7-9806-661a837d851d.png)

*Whoops, email responses don't support markdown*

**Comment by Baughn** [comment]
That's "undeclared" as in Curse metadata. It isn't listed on https://minecraft.curseforge.com/projects/extra-alchemy/relations/dependencies, which clients (Curse itself, and also my modpack-builder) use to download necessary dependencies.

You can specify dependencies when you upload files, see https://minecraft.curseforge.com/forums/general/general-discussion/12594-adding-dependencies-to-mods. If you use CurseGradle, it probably has options of its own for that.

**Comment by zabi94** [comment]
The point is, I specified the dependency as explained in the second link
you posted since the file existed on the curse server. That resulted in the
screenshot I posted...
Not sure why it doesn't show up in the dependencies section

Il 30 mag 2017 19:15, "Svein Ove Aas" <notifications@github.com> ha scritto:
