### ISSUE TITLE
Can I add Chinese language to this MOD?

### ISSUE THREAD

**Issue by QiYiJun** [zabi94/ExtraAlchemy#142]
I think I did something wrong before, I don't know if I can add a new language for this module, I hope to get your response.

**Comment by zabi94** [comment]
Sure, feel free to either open a pull request with the translation files, or just attach a translated json to this issue!

**Comment by QiYiJun** [comment]
> Sure, feel free to either open a pull request with the translation files, or just attach a translated json to this issue!

Thanks :)
