### ISSUE TITLE
Heat Sources don't provide fuel unless the Brewing stand is actively brewing

### ISSUE THREAD

**Issue by fxm84625** [zabi94/ExtraAlchemy#145]
**Describe the bug**
Magma blocks don't provide fuel until the Brewing stand is brewing.
Also tested with other heat sources: Campfire, Fire, and Lava.

**To Reproduce**
1. Place a Brewing Stand on top of a Magma Block
2. The Brewing Stand's fuel does not increase, and brewing isn't possible

Test:
1. Place a Brewing Stand on a non-heat-source block and insert Blaze Powder as fuel
2. Brew any number of times, leaving some fuel still in the Brewing Stand
3. Remove the block under the Brewing Stand and place a Magma Block under the Brewing Stand
4. The Brewing Stand's fuel doesn't increase
5. Start brewing while the Magma Block is under the Brewing Stand
6. The Brewing Stand's fuel increases while it's brewing

**Expected behavior**
When placing a Brewing Stand on top of a Magma Block, the fuel should increase passively.

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: 
 - Modpack link (preferred) or Mod List: https://pastebin.com/vv6Jg68G
 - Custom changes to modpack (if using a modpack):
 - Extra Alchemy Config: Default

**Environment (please complete the following information):**
 - Mod Version: 1.9.0
 - MC Version: 1.19.2
 - Fabric Version: 0.14.9
 - Fabric API version: 0.63.0
 - System: Windows 10
 - Installation type: Dedicated Server

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
If using the default config, you'll have brewingStandFireMaxCapacity set at 10 out 20.
This means that if you are above half heat, it won't recharge.
Try setting it at 20 to see if it fixes your issue

**Comment by MLMII** [comment]
Perhaps I'm misunderstanding the instructions on heat sources, but with the config set to 20 I'm having difficulities getting the brewing stand to first accept heat sources but once it does it seems to work; although I've never been able to get the stand to work with a slab covering the block.

**Comment by zabi94** [comment]
This one took me a lifetime to figure out.
Add  `mixin.world.block_entity_ticking.sleeping.brewing_stand = false` at the end of the "lithium.properties" file in your config folder server-side.
