### ISSUE TITLE
[Feature] EMIffect compat

### ISSUE THREAD

**Issue by Pirogiran** [zabi94/ExtraAlchemy#148]
EMIffect is EMI addon (recipe viewer) that provides information about potion effects.

![image](https://user-images.githubusercontent.com/99805468/207599965-416f1fef-3e75-4f89-9324-9f2a6ea001c4.png)

Compatibility is pretty easy to do (lang file change), and I would do it myself, but I don't have permission and the author's vision of what the descriptions of the effects should look like.

**Comment by zabi94** [comment]
This is unfortunately a very long task, I don't know when or if it will be implemented. If anyone wants to send a PR with description similar to what other mods do, I'll gladly merge it into the main branch.

**Comment by Pirogiran** [comment]
I think i figured out...
I will do something today/tomorrow.
![image](https://user-images.githubusercontent.com/99805468/207608769-43eb3396-2702-4ecc-b839-71e53bc6758d.png)
