### ISSUE TITLE
Crash when running alongside FTBUtilites and FTBLib

### ISSUE THREAD

**Issue by arfink** [zabi94/ExtraAlchemy#15]
BUG:

On bootup, the game will crash if I run extraalchemy-0.3.4-release (in 1.11.2) at the same time as FTBUtilities-1.1x-3.6.5 and FTBLib-1.1x-3.6.5, along with Janus. Reverting to extraalchemy-0.3.3.1-release with compatlayer will work, however. 

While the crashlog does not appear reference ExtraAlchemy, I figured I would bring it to your attention since it does appear from my testing to be a cross-mod compatibility issue. I will also report to the FTBLib/Utils folks if you believe it is not on your mod. 

This happens at bootup on client side, have not tested server side.
Minecraft 1.11.2

Crash log, includes full mod listing: https://pastebin.com/miz5AMz4
Configs for Extra Alchemy: https://pastebin.com/5kfvkCr4
Recipe config for EA is still default. 

Linux + Java 8

**Comment by zabi94** [comment]
The problem is that ftblib requires compatlayer, and when you update my mod you are removing it. You can install both CompatLayer and JanusLib together with no problems. That should solve it, but let me know

**Comment by arfink** [comment]
Excellent, thank you!
