### ISSUE TITLE
[Mod Compat]   Origins: Classes  "Cleric's Extended Potions" do not function with potion bag

### ISSUE THREAD

**Issue by MLMII** [zabi94/ExtraAlchemy#154]
In the Origins add-on Classes one of the selections is a 'cleric' who has the ability to make brewed potions 'extended' (doubling the potion's duration) using a cauldon.   The potion bag doesn't accept these potions as legitimate items to be selected, although they can be stored in the storage area of the bag.

Thank you for your time.

**Comment by zabi94** [comment]
The Origin: Classes mod uses an unorthodox method to lengthen the potions, which is done by including the effects in a custom potion tag. The bag can't recognize what potion a bottle contains, so it won't use them. I'll investigate if there's a way to determine which potion to use in a simple manner, but I make no promises
