### ISSUE TITLE
MemoryLeakFix is incompatible with this mod

### ISSUE THREAD

**Issue by Sunconure11** [zabi94/ExtraAlchemy#158]
https://github.com/fxmorin/MemoryLeakFix/issues/112#issuecomment-1585617103

**Comment by Sunconure11** [comment]
@zabi94 Just pinging as a reminder. The issue is mixin-related.

**Comment by zabi94** [comment]
Appears to be the same issue as in #159

**Comment by Sunconure11** [comment]
I had first spotted this on 1.19.2. Would bringing this fix there be feasible for you or are you not gonna bother?

**Comment by zabi94** [comment]
I really only update to latest version, I'd need to fork and cherrypick all the changes I've made since.
I'm completely burned out, and it takes me months to do even basic maintenance, so probably not.
