### ISSUE TITLE
Client crash on load

### ISSUE THREAD

**Issue by a-frenzy** [zabi94/ExtraAlchemy#16]
https://gist.github.com/frenzye/596c43c6b186b28cf8d872ca1b77337b

**Comment by zabi94** [comment]
This is forge being in its early 1.12 days. They are changing things around and it breaks compatibility with mods. Can you check if this happen with forge 14.21.0.2327 too?

**Comment by zabi94** [comment]
If this happens with 2327 too I'll also need you to compile the issue template, I'll need more data to fix

**Comment by MokahTGS** [comment]
Is this crash part of this?

https://pastebin.com/qAjFt0XE

This is on Forge 2389

If it is, hopefully it will help get it fixed.

**Comment by zabi94** [comment]
Yes, that's the same kind of issue. I'll update either tomorrow or the day
after

Il 02 lug 2017 22:53, "MokahTGS" <notifications@github.com> ha scritto:
