### ISSUE TITLE
[1.20.1] Guide book not loading correctly for patchouli

### ISSUE THREAD

**Issue by AubriTheHuman** [zabi94/ExtraAlchemy#161]
**Describe the bug**
When loading the game, the guidebook for ExtraAlchemy does not load properly, citing that "has use_resource_pack set to false" is no longer allowed in 1.20.

**To Reproduce**
1. Install ExtraAlchemy 1.10.0
2. Install Patchouli 1.20.1-83-FABRIC
3. Launch Game
4. Error thrown in log, and book does not appear in creative inventory.

**Expected behavior**
Guide book loads properly to explain mod to player.

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: [https://pastebin.com/8yVCaPpn](https://pastebin.com/8yVCaPpn)
 - Mod List: 
   - Patchouli 1.20.1-83-FABRIC
   - Fabric API 0.91.0+1.20.1
   - ExtraAlchemy 1.10.0
 - Extra Alchemy Config:
   - Default config:

**Environment (please complete the following information):**
 - Mod Version: 1.10.0
 - MC Version: 1.20.1
 - Fabric Version: 0.14.25
 - Fabric API version: Fabric API 0.91.0+1.20.1
 - System: Windows 10
 - Installation type: Minecraft Client

**Comment by mustbetommy** [comment]
Can confirm. I even came here to look at the source code to see if anything was missing. That's how I've been checking the potion effects. The guide book doesn't work.

**Comment by zabi94** [comment]
Yes, I haven't had the chance to upgrade the jsons for the books yet, when I updated the mod to newer versions Patchouli was not available yet so I never realized it was broken. I'll fix it up next week probably

**Comment by eileenthg** [comment]
Issue still persists on latest ExtraAlchemy 1.20.1 versions available on Curseforge and Modrinth. (Still on version 1.10.0). 

(I ended up fixing it manually myself but the server host I'm using (Aternos) is less flexible..)
