### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NoName1245** [zabi94/ExtraAlchemy#17]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(Crash)

---

#### Version of the mod or build number:
>(0.3.4)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(SP)

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(1.12)

---

#### Description (or what were you doing when it crashed):
>(Loading the game. This happened both on my normal 1.12 instance and a test instance that was only Forge and Extra Alchemy.)

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(https://pastebin.com/X0w71CQM)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(As this happened with only forge and the mod by itself in my testing, n/a)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(Config unmodified)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(Windows 10, Java 8 64 bit)

---

#### Other information that you think might be useful:
>(None)

**Comment by zabi94** [comment]
This is a known issue, caused by forge changing and being in its early 1.12 days... I'll release an update shortly
