### ISSUE TITLE
Crash on 1.12

### ISSUE THREAD

**Issue by Sunconure11** [zabi94/ExtraAlchemy#18]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Crash

---

#### Version of the mod or build number:
"The 1.12 update! READ CHANGELOG!", as stated by curse.

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Singleplayer

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
1.12

---

#### Description (or what were you doing when it crashed):
I tried to boot up MC and got this crash

https://pastebin.com/3G7m4EzQ

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):

It didn't even generate.

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

Java 8, windows 10

---

#### Other information that you think might be useful:
>(-)

Issue appears to be related to Tough as Nails, as well.

**Comment by zabi94** [comment]
Yup, it's a known bug, it will be fixed in the next version (eta unknown, I'm recovering from an injury)
