### ISSUE TITLE
Why was V0.3.4 pulled from curse?

### ISSUE THREAD

**Issue by Claycorp** [zabi94/ExtraAlchemy#19]
Also can you please keep the version in the file name so you know what version it is otherwise
the only want to know what version a file is to go to CurseForge and click on it...

**Comment by zabi94** [comment]
The version for 1.12 that was on curseforge was broken with the new recommended forge version, I removed it, no one could use it anyways. For previous versions, the latest available is up to date with bugfixes and content. 

I will add versioning if I decide to use a custom name again in the future
