### ISSUE TITLE
Suggestion for IE Automation

### ISSUE THREAD

**Issue by jjc54** [zabi94/ExtraAlchemy#20]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion

---

#### Version of the mod or build number:
>extraalchemy-0.3.4.1-release

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>SP

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12

---

#### Description (or what were you doing when it crashed):
>There is a feature in Immersive Engineering that allows you to mix up potions in a Mixer, and then bottle them in a Bottler. This feature is really cool for automating the production of potions from vanilla but it doesn't seem to work with the potions Extra Alchemy adds. I just wanted to suggest the integration if it was easy to implement.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>N/A

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>N/A

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>N/A

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>N/A

---

#### Other information that you think might be useful:
>Thanks for having a look at my suggestion! If IE is doing something crazy for the mixer don't worry yourself with the integration.

**Comment by zabi94** [comment]
I'll look into it and let you know

**Comment by zabi94** [comment]
There is no deobf version for 1.12 yet. As soon as one gets released I'll work on it

**Comment by prettyflyforapyguy** [comment]
It probably isn't that simple as other mods that I am aware of, do not work with it either.

However, it is possible to automate the brewing using vanilla brewing stands with extra utilities 2 and probably many other mods. Using flat transfer nodes with filters, you can place the stands next to each other, leaving a really compact brewing chain. You can also use transfer filters with a pipe and transfer node to limit the itemstack to 1 for an analog crafter which will craft phial rounds with the potion automatically too.

None of this uses power either, so the system works really well. I'm all for the integration too, but this is a good workaround if it isn't possible to integrate it.

**Comment by zabi94** [comment]
Given what CoFH and Thermal Expansion do now, I think that this feature won't be nearly as useful now

**Comment by zabi94** [comment]
Quick update: https://twitter.com/BluSunrize/status/1017324504614428672
