### ISSUE TITLE
Crash when searching potion in JEI and scrolling to third page

### ISSUE THREAD

**Issue by EnderMelody** [zabi94/ExtraAlchemy#21]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Crash

---

#### Version of the mod or build number:
>0.3.3.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Singleplayer

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.10.2

---

#### Description (or what were you doing when it crashed):
>Searched "potion" in JEI and scrolled through to page 3 and crashed to desktop.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://github.com/zabi94/ExtraAlchemyIssues/files/1338622/latest.log

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>Custom modpack
https://pastebin.com/C3Rbz5WL

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>https://pastebin.com/Zb7CHM5n

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>windows 10 + java 8

---

#### Other information that you think might be useful:
>https://pastebin.com/MVYtCS4G
was able to reproduce every time
Thank you for taking the time to make this mod and maintain it.

**Comment by zabi94** [comment]
The pastebin of the log is the wrong link I guess, there's a mod list inside instead

**Comment by EnderMelody** [comment]
oh opps, apparently the file was too big for pastebin and in didn't notice.
[latest.log](https://github.com/zabi94/ExtraAlchemyIssues/files/1338622/latest.log)

**Comment by zabi94** [comment]
Hmm. Try and disable rustic and botania integration from ea config and see if that happens again please

**Comment by zabi94** [comment]
Specifically, loadRusticPotions and loadBotaniaPotions should be both set to false

**Comment by EnderMelody** [comment]
Seems to be the same crash as before, so turning that off doesn't seem to have fixed it.
[crash-2017-09-28_15.07.11-server.txt](https://github.com/zabi94/ExtraAlchemyIssues/files/1342025/crash-2017-09-28_15.07.11-server.txt)
[crash-2017-09-28_15.07.11-client.txt](https://github.com/zabi94/ExtraAlchemyIssues/files/1342026/crash-2017-09-28_15.07.11-client.txt)
I also tried turning off vials/Breaking potions but that didn't help

**Comment by zabi94** [comment]
Ok thanks, I'll try and fix it. Might be some weird interactions with new
versions of rustic and botania

Il 28 set 2017 21:37, "EnderMelody" <notifications@github.com> ha scritto:

**Comment by zabi94** [comment]
Hopefully fixed in 0.3.5, it will be released soon

**Comment by EnderMelody** [comment]
I saw the hotfix for 1.12, but not 1.10, are you not updating 1.10 anymore? sorry if you already said this.

**Comment by zabi94** [comment]
Yes, development for pre 1.12 has stopped

Il 12 ott 2017 04:24, "EnderMelody" <notifications@github.com> ha scritto:
