### ISSUE TITLE
Is it possible to remove vanilla (and other mods) potion recipes?

### ISSUE THREAD

**Issue by stohun01** [zabi94/ExtraAlchemy#25]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion
---

#### Version of the mod or build number:
>0.3.6
---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2
---

**Comment by zabi94** [comment]
It's not, I think this is something more fitting for a mod like crafttweaker
