### ISSUE TITLE
No recipes in JEI

### ISSUE THREAD

**Issue by ghost** [zabi94/ExtraAlchemy#26]
Recipes for the Extra Alchemy potions do not appear in [JEI](https://minecraft.curseforge.com/projects/just-enough-items-jei).

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm) ([version 1.4](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm/files/2499719))
**Minecraft version**: 1.10.2
**Forge version**:  12.18.3.2511
**Extra Alchemy version**: 0.3.3.1
**Just Enough Items version**: 3.14.7.420

**Comment by zabi94** [comment]
Support for older minecraft versions has been dropped, unfortunately

**Comment by ghost** [comment]
So you won’t even fix a bug that prevents people from seeing the recipes? 😕

**Comment by zabi94** [comment]
My hard drive broke, and all the old branches (pre 1.12 code) have been
lost, since they were not in a remote repo, sorry, nothing I can do about
them.

**Comment by ghost** [comment]
Well, that sucks.

How do I get the recipes, then? [Your wiki](https://github.com/zabi94/ExtraAlchemyIssues/wiki/Potions) has no recipes!

**Comment by zabi94** [comment]
Read the potions page better, they are there :P

**Comment by ghost** [comment]
Where?

**Comment by zabi94** [comment]
Literally in the description of every single one of them...

**Comment by ghost** [comment]
I can’t see them.

**Comment by zabi94** [comment]
Taken from the potion of fuse: 
``` 
When this effect runs out, the entity explodes. Kaboom. Best use is arrow form, to get that extra bit of damage when they least expect it (2 seconds after being hit by the arrow, that is. Maybe not that unexpected actually). This is actually one of the exception to the redstone rule, since it gets shortened by it, instead of extended. Craft it with any firework star in an awkward potion 
``` 
Last phrase  

*Craft it with any firework star in an awkward potion*

**Comment by ghost** [comment]
That’s the only one with a recipe.

**Comment by zabi94** [comment]
Did you even bother reading it? Like, the **whole** thing for the potion you want. Every single one of them has it, somewhere in its description

**Comment by ghost** [comment]
Oh. I get it now. The recipes are always different. I expected either a simple sentence at the end or images. Thanks.

Still, it’d be a lot easier to have the recipes in JEI.

**Comment by DanHulton** [comment]
For what it's worth, there's no recipes for JEI in Minecraft 1.19.2, either, latest version of mod and Fabric.

Is it just that JEI won't be supported?

**Comment by zabi94** [comment]
Last I checked, they worked. Please open a new issue, it's likely a different bug
