### ISSUE TITLE
Alchemy Bag not showing item names

### ISSUE THREAD

**Issue by Skalfred** [zabi94/ExtraAlchemy#27]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Bug

#### Version of the mod or build number:
>ExtraAlchemy-0.3.6

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Multiplayer Client

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>N/a

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>N/A

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>[Modpack](https://minecraft.curseforge.com/projects/magiculture-2?gameCategorySlug=modpacks&projectID=282334)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>[Pastebin](https://pastebin.com/zkk2psbx)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
> Java 8 + Windows 8.1

---

#### Other information that you think might be useful:
>Just when you open the alchemy bag none of the items have names when you hover over them.

**Comment by zabi94** [comment]
Thanks for the report
