### ISSUE TITLE
[1.10.2] Custom recipes doesn't work

### ISSUE THREAD

**Issue by prettyflyforapyguy** [zabi94/ExtraAlchemy#28]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Crash

---

#### Version of the mod or build number:
>extraalchemy-0.3.3.1-release

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Game doesn't start but both usually

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.10.2

---

#### Description (or what were you doing when it crashed):
>Before launching I tried adding a potion recipe

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://pastebin.com/raw/qDqsAY5f

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>Is included with log

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>default config

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Java 8 + Win 7

---

#### Other information that you think might be useful:

I tried adding many recipes, none of them worked.

The example given:
>minecraft:awkward&minecraft:dye,3=minecraft:strong_healing

does not work.

When i set the itemstack to an invalid item, the game does not crash, but the recipe is not added.

While this was observed on an older version, it might potentially apply to newer ones. I can't update to verify it though. It would be really cool to actually use a magnet provided by another mod I have rather than using an iron ingot for a potion of magnetism.

**Comment by zabi94** [comment]
It's probably a forge update that broke something, that's my best guess. I'm in the process of rewriting the mod anyways for 1.12+ so I'm not even gonna bother seeing if it's a bug or not in more recent versions for now
