### ISSUE TITLE
[Suggestion] Why not combine effects? Transfer content? Dilute effects?

### ISSUE THREAD

**Issue by alpharou** [zabi94/ExtraAlchemy#29]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion

---

#### Version of the mod or build number:
>extraalchemy-0.3.6-release

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Both, doesn't matter

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>It did not crash, is just a suggestion.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Java 8, Win10

---

#### Other information that you think might be useful:
>Why combining effects is not allowed? It could make this mod extremely more versatile, in my opinion... Think of it this way. I want to prepare for battle, now, I already have stacked vials, nice. I also have alchemy bags filled to the brim with them, NOICE! But I have at least three different alchemy bags on me at any time, :/. I understand it could get really OP really quickly, but by combining effects the duration is decrased a 20% (or any other value) per effect added. Also, you would need something more powerful than a slime ball to combine them this way... oh I know! why don't we use magma cream! The heat from the blazing content concentrates the mixture and blends the properties irreversibly, at a cost.

>Also, splitting potions using water bottles (or water splash potions/lingering and create a vial filled with water) instead of empty bottles makes sense doesn't it? Sort of like diluting the content of the potion into water vial/splash/lingering/regular that are crafted with the original.

>Why don't also include empty recipes for splash and lingering potions in the brewing station? (Empty bottle + gunpowder = empty splash bottle, throwable the same way as a regular splash, just nothing happens.) This way you could craft a potion with this empty ones to transfer the mixture safely the same way you do with the vials, just more flexibly and reversibly.

**Comment by zabi94** [comment]
I'd rather keep the mod simple, honestly, most of the stuff you suggested would require a lot of infrastructure, I feel like it goes beyond the scope of this mod
