### ISSUE TITLE
[Bug]: Issue with COFH Instant potions

### ISSUE THREAD

**Issue by Akitori** [zabi94/ExtraAlchemy#31]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(Bug)

---

#### Version of the mod or build number:
>(extraalchemy-0.3.6.1-release)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(Single Player)

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(1.12.2)

---

#### Description (or what were you doing when it crashed):
>(I was experimenting with Extra Alchemt and Thermal Expansion, along with COFH mods. I used the vial from Extra Alchemy to use Instant health 3 potions from COFH. However, this didn't work as intended, only resulting in the vial shattering, but no health being restored.)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(https://pastebin.com/9wFpzhWR)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(https://pastebin.com/HU3uEGa9)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(Windows 10, Java 8 build 151)

---

#### Other information that you think might be useful:
>(https://youtu.be/1Mt2zZYNOe0)

**Comment by zabi94** [comment]
Fixed in 0.3.6.2
