### ISSUE TITLE
Now It Crashed When Doing The Same Recalling 

### ISSUE THREAD

**Issue by FlickySH** [zabi94/ExtraAlchemy#32]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)

Crash

#### Version of the mod or build number:
>(*)

0.3.6.1

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)

Single Player

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)

1.12.2

#### Description (or what were you doing when it crashed):
>(*)

Did the same recalling process, now when I am being teleported, (Loading Terrain) it crashes.
Plz fix it
Thanks

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

https://mega.nz/#!hfQ3SJiQ!kYCmTeoaGd95Dc2Dj7iXdF8w8hA39CAlOn9htKcyHCQ
Reached thee max of 512 kb so I have uploaded it to my cloud.

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

Same from my prev issue

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

Same from my prev issue

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

Java 8 + Windows 10

#### Other information that you think might be useful:
>(-)

java.lang.NoClassDefFoundError

**Comment by FlickySH** [comment]
R u there, hello

**Comment by zabi94** [comment]
I have a life outside modding, I cannot offer 24/7 support, you need to be patient ¯\\\_(ツ)_/¯

**Comment by FlickySH** [comment]
OK Thx, didn't mean to bother, hope it will be fixed soon

**Comment by Aregev2** [comment]
OK Thx, didn't mean to bother, hope it will be fixed soon

**Comment by zabi94** [comment]
I will, don't worry ;)

**Comment by zabi94** [comment]
Fixed in 0.3.6.2, incoming on curseforge

**Comment by FlickySH** [comment]
omg thx

2018-01-18 14:14 GMT+02:00 ZaBi94 <notifications@github.com>:
