### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Sunconure11** [zabi94/ExtraAlchemy#33]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Crash

---

#### Version of the mod or build number:
>0.3.6.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Serverside

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>I was attempting to boot up my server.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://pastebin.com/yB34ixJx

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>https://minecraft.curseforge.com/projects/compitum-magia

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>https://pastebin.com/3naPr4vx

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Windows 10 and java 8

---

#### Other information that you think might be useful:
>(-)

**Comment by Sunconure11** [comment]
User error, please ignore.

**Comment by FlickySH** [comment]
Same exception as mine

**Comment by zabi94** [comment]
Same exception, different bug though

**Comment by zabi94** [comment]
fixed in 0.3.6.2

**Comment by FlickySH** [comment]
Is it up in curse?

**Comment by zabi94** [comment]
If you can't find it it's probably awaiting approval
