### ISSUE TITLE
Vials do not work with normal potions.

### ISSUE THREAD

**Issue by Insane96** [zabi94/ExtraAlchemy#34]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion

---

#### Version of the mod or build number:
>0.3.6.2

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>SP

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>Vials don't work with normal potions but only with splash ones and that is not documented anywhere.

**Comment by zabi94** [comment]
I'll update the description, thanks
