### ISSUE TITLE
Combined potions should have the original potion color

### ISSUE THREAD

**Issue by Insane96** [zabi94/ExtraAlchemy#35]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion

---

#### Version of the mod or build number:
>0.3.6.2

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Both

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>Make combined potion have the right potion color and not that purple-ugly-like color

**Comment by zabi94** [comment]
It's a known visual bug (see curseforge page). 
Thanks for the report anyways
