### ISSUE TITLE
Config is broken

### ISSUE THREAD

**Issue by FlickySH** [zabi94/ExtraAlchemy#37]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)

Bug

#### Version of the mod or build number:
>(*)

0.3.7.1

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)

Singleplayer

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)

1.12.2

#### Description (or what were you doing when it crashed):
>(*)

Config is broken, glowing effect isnt being removed no matter what the config is
plz fix it (ez fix  i guess)

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

https://pastebin.com/4019xBrY

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

https://pastebin.com/mWC9LG3z

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

Java 8 + Windows 10

#### Other information that you think might be useful:
>(-)

**Comment by FlickySH** [comment]
Im so dumb, it moved to another mod
💯

**Comment by zabi94** [comment]
It's not broken, the feature has been moved to its own mod, and is no longer in extra alchemy. Check out [NoMoreGlowingPots](https://minecraft.curseforge.com/projects/nomoreglowingpots)
