### ISSUE TITLE
[Request] Brewing Stand Heat Source Whitelist

### ISSUE THREAD

**Issue by ElvenChaos** [zabi94/ExtraAlchemy#38]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Feature Suggestion

---

#### Version of the mod or build number:
>0.3.8

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>All of the Above.

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description:
>There should be an option in the configs to describe a whitelist of blocks, tile entities, and liquids that can act as a heat source for the brewing stand, similar to how fire and lava can be used.

---

#### Other information that you think might be useful:
>Examples of reasonable additions that someone editing a whitelist could include would be along the lines of magma blocks, pyrotheum from thermal expansion, chisel lava bricks, tcon lavawood, thaumcraft nitor (when available), etc. This could also be useful to a pack creator that wants to add an unintuitive heat source for any reason.

---

**Comment by zabi94** [comment]
The problem with that is performance. Currently the brewing stand tweak is one of the most laggy things in the mod, this becomes especially noticeable when you have a high number of tile entities. 
I hope to find a way to rewrite it that is not as laggy, but I fear that the only option for that is asm/coremods

**Comment by ElvenChaos** [comment]
While it is generally good to avoid core mods, I don't think there is any other mod that even touches the brewing stand itself, so I think it would be a safe one. That said, I'm by no means an expert on these things.

I don't know how often you are checking the block below the stand, but you should only have to check it on a block update. Again, I'm not an expert at this.

**Comment by zabi94** [comment]
I'm not going to make a core mod, that's for sure, I just removed the only bit of asm from it.

And unfortunately, no, checking on block updates is not enough, it needs to be done every number of ticks

**Comment by ElvenChaos** [comment]
Would making your own brewing stand let you avoid making a core mod while getting the tweaks you want in? You could just make your own, and have its crafting recipe include (or just be) the vanilla brewing stand, so that you are not hijacking or messing with the vanilla brewing stand.

**Comment by zabi94** [comment]
That would collide with the mod philosophy of being an extension to vanilla
alchemy

**Comment by ElvenChaos** [comment]
If the feature can be re-coded to be more efficient with its current functionality, that would be the ideal.

However, if it couldn't, would the trade-off be worth it performance-wise? Even if I used the theoretical new brewing stand, the alchemy would still be the same, as well as most of the GUI (minus the blaze powder).

**Comment by Nakuta** [comment]
If whitelisting various heat sources from other mods is a problem, perhaps a compromise would be to allow the use of additional fuels in the blaze powder slot to fuel the brewing stand.  The primary issues with needing blaze powder are both its rarity as well as the competition for its use in other recipes. Being able to use coal/charcoal/etc. to fuel the brewing stand would feel much less punitive.

**Comment by zabi94** [comment]
That requires coremods, unfortunately, so it's not going to happen
