### ISSUE TITLE
[Request] Return an empty glass vial to the player 

### ISSUE THREAD

**Issue by NotAVerb** [zabi94/ExtraAlchemy#40]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Feature Request 
---
#### Version of the mod or build number:
>0.3.8.1
---
#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2
---
#### Description :
>I'd like for the potion vials to return an empty vial to the player upon use.
---
#### Other information that you think might be useful:
>Spit the vial out into the world if the players inventory is full.

**Comment by zabi94** [comment]
Why though? This would completely nullify their cost, effectively offering a free upgrade... 
Plus the idea is that you shatter the vial on yourself to get the effect faster, returning it would be counter intuitive

**Comment by NotAVerb** [comment]
Without making recipe changes, vials currently remove two blocks of sand from the game per use.

I actually thought the vials were sort of like shot glasses, and that because the potions are the same liquid in splash potions less of the actual potion was required for the effect.
Which brings up a point showing how vials are not without a cost beyond losing the vials. You still have to expend gunpowder.

This of course could be a config option that is off by default.
