### ISSUE TITLE
[Request] make this mod work with thermal expansion's alchemy machines

### ISSUE THREAD

**Issue by lag42** [zabi94/ExtraAlchemy#45]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Request

---

#### Version of the mod or build number:
>0.3.8.5-release

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>it would be nice if you could get the alchemical imbuer and the alchemical quiver from thermal expansion/innovation working with your potions

**Comment by zabi94** [comment]
There should already be support: https://github.com/CoFH/ThermalExpansion/blob/7c2d68629c6d8435479eb82c010364ef3f1f8bc8/src/main/java/cofh/thermalexpansion/plugins/PluginExtraAlchemy.java
Is it not working for you?

**Comment by lag42** [comment]
it appears to be working fully now
I have no clue why it wouldn't work before
