### ISSUE TITLE
Spanish Translate (Beta)

### ISSUE THREAD

**Issue by LordBerial** [zabi94/ExtraAlchemy#47]
https://pastebin.com/1Z8H3GDX

**Comment by zabi94** [comment]
I see that you are using accents. They might render weird in 1.12 and previous versions. How does vanilla minecraft handle those?

**Comment by LordBerial** [comment]
Vanilla and the Ice and Fire mod use them without problems. They can always be removed if they cause conflict. We do what you decide 😄
________________________________
De: ZaBi94 <notifications@github.com>
Enviado: sábado, 13 de octubre de 2018 18:33
Para: zabi94/ExtraAlchemy
Cc: LordBerial; Author
Asunto: Re: [zabi94/ExtraAlchemy] Spanish Translate (Beta) (#47)


I see that you are using accents. They might render weird in 1.12 and previous versions. How does vanilla minecraft handle those?

**Comment by zabi94** [comment]
Yup, accents work fine. Maybe it was changed after 1.9.
Next version will have Spanish localization

**Comment by LordBerial** [comment]
I'll probably send you a corrected version when the new version is up in the air. Yay :D
________________________________
De: ZaBi94 <notifications@github.com>
Enviado: miércoles, 17 de octubre de 2018 12:56
Para: zabi94/ExtraAlchemy
Cc: LordBerial; Author
Asunto: Re: [zabi94/ExtraAlchemy] Spanish Translate (Beta) (#47)


Yup, accents work fine. Maybe it was changed after 1.9.
Next version will have Spanish localization
