### ISSUE TITLE
CME server crashes

### ISSUE THREAD

**Issue by ProsperCraft** [zabi94/ExtraAlchemy#48]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)
Bug
---

#### Version of the mod or build number:
>(*)
extraalchemy-0.3.8.6.1-release
---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)
Server Side
---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)
1.12.2
---

#### Description (or what were you doing when it crashed):
>(*)
Server saving chunks, this trace was from logging in while a special mod is running on the server to find this problem.
---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)
https://gist.github.com/ProsperCraft/5d552827c6a30b87051073bbfb71ad72
[ancienttowncraftlogs.zip](https://github.com/zabi94/ExtraAlchemy/files/2523956/ancienttowncraftlogs.zip)

I started the investigation because I kept getting this- even when there were no players on-
https://gist.github.com/Potato-bot/47f3b6e6d3d4be8f33018a2a7ba31e5d

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)
https://minecraft.curseforge.com/projects/ancient-towncraft/
---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)
https://gist.github.com/ProsperCraft/a52387ff33440191141a0178997ebceb
---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)
openjdk version "1.8.0_191"

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
Backup your world, remove extra alchemy, start and stop your server. Does it still crash?

**Comment by zabi94** [comment]
News?

**Comment by ProsperCraft** [comment]
I removed it from the pack, which stopped the crashing.
