### ISSUE TITLE
I want to help with the Spanish Translation

### ISSUE THREAD

**Issue by Paiadidaisada** [zabi94/ExtraAlchemy#49]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---Hi there, I would like to help with the Spanish translation of the mod (if there is no one already working on it), and, if im allowed to, giving some ideas to expand the mod, i would really like to see it grow as its such an awesome job!

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)

---Translation

#### Version of the mod or build number:
>(*)

---0.3.8.5

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)

--- Single player

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)

---1.12.2

#### Description (or what were you doing when it crashed):
>(*)

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

---

#### Other information that you think might be useful:
>(-) I will log in this page first days, but i cant really be here waiting for an answer if you take too much time, so... maybe after a week, i would only see your responses with my email (diegosanisiclavero@gmail.com), if its easier for you to talk to me that way is cool too. Good luck, you are doing a great job!

**Comment by zabi94** [comment]
Sorry for the long time, I've been too busy lately. A spanish translation is in the mod already
