### ISSUE TITLE
[Suggestion] Alchemy Bag Interactions with Split/Combined Potions and Vials

### ISSUE THREAD

**Issue by Nakuta** [zabi94/ExtraAlchemy#51]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Suggestion

---

#### Version of the mod or build number:
0.3.8.6.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Single Player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
1.12.2

---

#### Description:
I tested out this mod for the first time, and I noticed that split/combined potions cannot be used with the Alchemy Bag, nor can potions that have been split and then re-combined to their original duration. Additionally, vials cannot be used with the Alchemy Bag either.

I'd like to suggest that all of the above be able to be used in conjunction with the Alchemy Bag, as it seems odd that core features of the mod don't work with one another. The current limitations significantly impact the utility of the Alchemy Bag in my opinion.

**Comment by zabi94** [comment]
Partially implemented for vials, v0.4.0, shortly available on curseforge
