### ISSUE TITLE
[Suggestion] Alchemy Bag Interface

### ISSUE THREAD

**Issue by Nakuta** [zabi94/ExtraAlchemy#52]
---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Suggestion

---

#### Version of the mod or build number:
0.3.8.6.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Single Player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
1.12.2

---

#### Description:
The alchemy bag interface is awkward to use while in combat. In order to use a potion of choice, a player must:

1. Shift-rightclick to open the Alchemy Bag interface.
2. Drag the potion of choice to the top slot.
3. Close the Alchemy Bag interface.
4. Hold rightclick to drink the selected potion.

Using a generic backpack or inventory container mod, a player could instead:

1a. Open the inventory screen and click to open the container interface.
1b. Open the container interface directly from the hotbar.
2. Drag the potion of choice to the hotbar.
3. Close the container and/or inventory interface.
4. Select the potion and hold rightclick to drink.

As compared to the Alchemy Bag, a backpack/inventory container takes either one additional hotbar space or requires one additional step to move a potion from storage to the hotbar. The Alchemy Bag has the advantage of allowing you to chain-drink a pre-arranged series of potions to buff up for a difficult battle without wasting time moving potions to the hotbar repeatedly. A backpack/inventory container has the advantage of holding items beyond just personal potions, including splash, lingering, split, combined and vial potions (all of which the Alchemy Bag currently cannot).

The Alchemy Bag feels very limited and only excels at one specific task (chain-drinking a specific series of potions to buff yourself before a fight).  I'd like to suggest an improvement the interface that allows the use of a radial menu to quickly select the next potion to be drunk, similar to how the Witchery mod's Brew Bag or Tool Belt's tool belt functions.  Having Baubles compatibility would also be a plus to give the option of saving room on the hotbar.

Thank you for your consideration of this suggestion.

https://sites.google.com/site/witcherymod/brew-bag
https://minecraft.curseforge.com/projects/tool-belt

---

**Comment by mmmilord** [comment]
I'd like to add onto this topic with a TL;DR of what the OP is hinting at. You would press a hotkey, a radial menu would come up, and you could select a potion/vial from a list of the Alchemy Bag inventory itself. (can be limited to only first 5-6 slots to make it simple). Selecting one, would only change the "ghost" item in it's top slot, letting you simply right-click bag. That would be a faster way of changing the active potion, to make it usuable in combat. You would have to sneak right-click to access it's inventory in the normal way, to put in potions.

Here is a poorly edited demonstration video of the concept.

https://www.youtube.com/watch?v=zk8dDYt0au0&feature=youtu.be

If you are interested here is ToolBelt's Github, and MineMenu that use "radial menus"
https://github.com/gigaherz/ToolBelt
https://github.com/GirafiStudios/MineMenu

**Comment by zabi94** [comment]
Yes, I know this is taking long to implement, I'm debating if I really want to add this feature, because my time is limited and such feature might imply I need to drop support for older versions.

Just as a heads up: you linked forge mods, while this is a fabric mod on newer versions. 1.12.2 won't receive new features, support is limited to bugfixing.

That said I don't really like radial menus, and I have a better looking alternative in mind already

**Comment by mmmilord** [comment]
Fair enough, I'm actually a 1.12 player, that's why I posted it. Thanks for reading anyway!
