### ISSUE TITLE
Crash when starting the game/joining a new world

### ISSUE THREAD

**Issue by ReeCodes** [zabi94/ExtraAlchemy#55]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(Crash)

---

#### Version of the mod or build number:
>(0.3.8.6.1)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(Singleplayer)

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(1.12)

---

#### Description (or what were you doing when it crashed):
>(Starting the game. It only happens randomly)

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(Since it only happens randomly, the least I can give you is the crash-report.

https://gist.github.com/ReeCodes/b9fc97b0a114295c7d5ca3a969a55a98
)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(https://minecraft.curseforge.com/projects/a-punch-of-mobs-respawned/relations/dependencies)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(https://pastebin.com/SQ7cyLMK)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(Java8 + Windows10)

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
I might need the latest.log file to understand what's happening

**Comment by ReeCodes** [comment]
If it happens again I will post the log

**Comment by zabi94** [comment]
Closing, since the relevant code has been moved to minerva
