### ISSUE TITLE
CompatLayer for minecraft 1.9.4

### ISSUE THREAD

**Issue by ghost** [zabi94/ExtraAlchemy#57]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(crash)

---

#### Version of the mod or build number:
>0.3.1.5.1-beta)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(single player)

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(1.9.4)

---

#### Description (or what were you doing when it crashed):
>(launching minecraft)

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://pastebin.com/v00zx96z)

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(https://imgur.com/a/wS9WgaK)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(https://imgur.com/a/wS9WgaK)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(win 10 Java is version 1.8.0_51, using 64-bit architecture.)

---

#### Other information that you think might be useful:
>(i am using multimc)

**Comment by zabi94** [comment]
1.9.4 support was dropped almost 2 years ago
