### ISSUE TITLE
Asking for Repost Permission

### ISSUE THREAD

**Issue by P1nWheel0v0** [zabi94/ExtraAlchemy#58]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Asking for Repost Permission
---

#### Version of the mod or build number:
0.3.8.6.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Single Player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
1.12.2

---

#### Description (or what were you doing when it crashed):
Hi, my name is PinWheel, I really like your mod. I wonder if I can repost this mod on MCBBS which is the largest Chinese Minecraft forum. Due to the barrier of language, most Chinese players are not able to play or even find this great mod. Thus I would like to introduce this mod to more Chinese players so that they can enjoy your mod as well. I will also help with the zh_CN.lang file update on your Github.
The entire repost will obey the rules list below and your own special requests.

- I will NOT take any credits of the mod and I will clearly state your official website (Curseforge and Github) at the head of my repost page.

- I will give the official download link directly and clearly note that "This is the official download link, please click here first"

- (Optional) In a case of the network firewalls (government policy stuff...) and network speed, I probably prepare another mirror link for backup. The mirror will direct to an Ad-free page (very like Dropbox).

- Last but not least, I will not use this mod to get profit/benefit in terms of money, etc... And I will clearly state that anyone who uses this mod must not use it to make money.

I will be really appreciated if you can give me permission.
Anyway, thank you for bringing us such an amazing mod and so much fun.

Yours sincerely,
PinWheel

---

**Comment by zabi94** [comment]
[The mod should already be available](http://www.mcbbs.net/thread-617911-1-1.html)

If it's too old, you have permission to repost according to the above conditions
