### ISSUE TITLE
[Bug] Combined Potions + Extra Alchemy

### ISSUE THREAD

**Issue by Akitori** [zabi94/ExtraAlchemy#62]
---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Bug

---

#### Version of the mod or build number:
>0.5.1

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Single Player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>Not necessarily crashed, just odd effect when using the two mods.
I was using Extra Alchemy with Combined potions. I tried to use a combined potion (in this case, fire resistance, jump boost, and regeneration) with the combining effect from your mod. However, that resulted in only one item getting the extended duration.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://pastebin.com/DEaWmxWK (placebo did some log spam, so i cut all that out)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>https://pastebin.com/cmFhuQ8Q

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>https://pastebin.com/hQ4rwQec

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Windows 10 + Java 8

---

#### Other information that you think might be useful:
>Think its related to what the last potion combined was.

**Comment by zabi94** [comment]
Potion combining is not meant to be used with multiple effects. I'll add a check next version to prevent them from combining

**Comment by EpsilonNetwork7** [comment]
Hello, can the 1.12.2 forge version source be uploaded here?

Thanks in advance.
