### ISSUE TITLE
[Suggestion] Press key to activate rings.

### ISSUE THREAD

**Issue by shoverno2** [zabi94/ExtraAlchemy#63]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(Suggestion)

---

#### Version of the mod or build number:
>(0.5.1)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(single player, Multiplayer, whatever)

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(1.12.2)

---

#### Description (or what were you doing when it crashed):
>(It's unconfortable to "turn off" ring effect)

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)

---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
Given how there's a switch that stops them from using XP when not active (eg, magnetism, photosynthesis), and that they are meant to be used for long lasting, uninterrupted effects, this won't likely be implemented
