### ISSUE TITLE
Suggestion: Disabled potions aren't registered at all

### ISSUE THREAD

**Issue by katubug** [zabi94/ExtraAlchemy#65]
#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Suggestion

---

#### Version of the mod or build number:
>EA 0.5.2, Minerva 1.0.13, Forge 2847

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Singleplayer

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.12.2

---

#### Description (or what were you doing when it crashed):
>I'm working on a modpack and there are several potions I'd like to have disabled. I don't mind hiding them in JEI via CraftTweaker, but ideally it would be fantastic if, when they were disabled, they were completely deregistered instead of simply having their recipes removed, similarly to how PotionCore does it.

In any case, thank you for the excellent mod, I'm excited to play with it some more. Have a lovely holiday!

**Comment by zabi94** [comment]
Can you explain why you want that? Removing the potion while keeping it registered is safer for the world save in case of changes

**Comment by katubug** [comment]
That's true, but since I'm working on a curated pack, I don't expect users to change their config after world creation.

My primary reason is that for each effect, there are many items to hide from JEI, which I generally do via script because the native JEI hiding is easy to undo, even by mistake.

But additionally, potion effect IDs and the items themselves count against the registry quota, so in larger packs, it could mean the difference between needing to add something like JEID to retain function.

Ultimately, it's not the biggest deal, as it isn't too hard to workaround, and I'm not sure how much work it would be to change. But those are the reasons why I suggested it.

Thanks for your response! I appreciate your time. :)

**Comment by zabi94** [comment]
The registry quota is something I predicted might happen and I made a mod that takes care of that, without any other extension that mods like jeid might apply, see [maxpotionidextender](https://www.curseforge.com/minecraft/mc-mods/max-potion-id-extender) on curseforge.

Hiding problems in JEI are, in my opinion, an acceptable compromise to have a stable save file.

**Comment by katubug** [comment]
Ah, thanks for the link!

And okay, that seems reasonable to me. Thank you for taking the time to consider this. Hope you have a good holiday, and thanks again for the mod!
