### ISSUE TITLE
[Suggestion] potion effect like recall explanation in comments

### ISSUE THREAD

**Issue by yukinagatosc2** [zabi94/ExtraAlchemy#66]
1.12.2 if possible, if not oh well

So the recall potion essentially sets a waypoint when it is drunk and teleports you back to it once it ends.  What I'm thinking is something similar but more akin to what happens when the server and client desync and anything that the player did during the desync is undone once things return to normal.  So basically imagine that you drink the potion and mine blocks under you and fall into a lava lake- once the potion effect ends either in "death" or at its expiration the player is teleported back to the starting point but anything they did while the potion was active is undone.  So in the example, you would know there was a lava lake under you without actually putting yourself in danger.

**Comment by zabi94** [comment]
This is extremely difficult to code, heavy on the resources and prone to bugs, not to mention that it would likely require a core mod, which I try to avoid in forge.

The idea would be cool, but it's unfortunately unfeasible.
