### ISSUE TITLE
Try to add E.A's potion effect to another mod trough JSON file [Doesn't work]

### ISSUE THREAD

**Issue by PickyPixelStudio** [zabi94/ExtraAlchemy#67]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
> Issue with another mod.

---

#### Version of the mod or build number:
> ExtraAlchemy : 0.5.2

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
> Single Player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
> Minecraft : 1.12.2

---

#### Description (or what were you doing when it crashed):
> After long research, I haven't figured out how to add a potion effect from ExtraAlchemy to another mode for creating our own armor sets. Called RealisticArmorTiers, however, I use the same name as the logs ...
For effects from Minecraft, or PotionCore, everything works, but not those from ExtraAlchemy.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
> [Crash Log](https://pastebin.com/hCmKK5pW)

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
> [Mods List](https://pastebin.com/MWaFLrKf)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
> [ExtraAlchemyCFG](https://pastebin.com/RQ18Wmws)

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
> Java8 Update221 + Windows 10

---

#### Other information that you think might be useful:
> ReallisticArmorTiers JSON look like this : [JSON Working](https://pastebin.com/6UgARQQp)
Gear sets called "Wool", with some potion effect. This one working well.
But this one, doesn't work at all : [JSON Not Working](https://pastebin.com/qRLtL7ch)

If you need to see my entire JSON file from ReallisticArmorTiers : [Here](https://pastebin.com/ub2wmRsb)

Thanks by advance.
NB : my english is not really accurate, don't blame me.

**Comment by zabi94** [comment]
You are using magnetism_normal which is a potion **type**, not a potion.

You can only use potion names, the same that you get when you hit tab when writing a `/effect extraalchemy:` command, in your case "extraalchemy:effect.magnetism" if I recall correctly. 

Let me know if that solves your problem.

**Comment by PickyPixelStudio** [comment]
Yep!

All effect from Extra Alchemy work perfectly.
Thanks a lot for your help <3

PS : I need to close this issue?! I never use github before...

**Comment by zabi94** [comment]
I'll do that, don't worry
