### ISSUE TITLE
[Bug] Incorrect Potion

### ISSUE THREAD

**Issue by NeonPhoenix** [zabi94/ExtraAlchemy#70]
---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Bug

---

#### Version of the mod or build number:
Version 0.5.3

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Singleplayer and Multiplayer

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
Version 1.12.2

---

#### Description (or what were you doing when it crashed):
When making a potion and using Better With Mods' Brimstone, recipes under JEI are to go to the second level, they however, it changes to Fuse II

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):

Modpack is Engineers Life

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):

https://pastebin.com/wRrRbXfw

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
Java 8 + Windows 10

---

#### Other information that you think might be useful:
https://imgur.com/Lqa2djA
https://imgur.com/M0lSOYE
https://imgur.com/B4lMumn

**Comment by zabi94** [comment]
I can see multiple problems actually... Like the tooltip saying that the potion is added by immersive engineering

**Comment by zabi94** [comment]
Anyways, that recipe has been added by the modpack creator, it's not a default recipe. I'll check to see if it's actually a bug in the mod, but my money is on a wrong recipe configuration

**Comment by NeonPhoenix** [comment]
I did notice that myself, I am sure there is some recipe change affecting it to some degree.

But I was not able to find where this recipe is being changed, the added by Immersive Engineering might be due to the bottler.

Is the combustion potion added by Extra Alchemy?

**Comment by zabi94** [comment]
Yes, the potion is by extra alchemy, the recipe with brimstone is not

**Comment by NeonPhoenix** [comment]
I will continue to dig around and find out what's happening on my end

**Comment by zabi94** [comment]
This is almost guaranteed to be a misconfiguration of the modpack, but I cannot track where this change is applied. I suggest asking the pack maintainer directly
