### ISSUE TITLE
Getting rewind potion effect crashes the game.

### ISSUE THREAD

**Issue by StriletsGlib** [zabi94/ExtraAlchemy#77]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash ):
Crash

---

#### Version of the mod or build number:
1.16-1.0.1-1.jar

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Single Player
---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
All 1.16 snapshots I tried; 1.16 Pre-3

---

#### Description (or what were you doing when it crashed):
Getting rewind effect using commands and potions crashes. HAVING this effect after reloading doesn't cause a crash

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
https://pastebin.com/A03iJW3x
---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):

  [✔️] fabric-api-0.11.9+build.358-1.16
  [✔️] localextraalchemy-fabric-1.16-1.0.1-1 (1)

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
https://pastebin.com/H6YDfRQT
---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
macOS 10.14.6
---

#### Other information that you think might be useful:
>(-)

**Comment by DoltenBolten** [comment]
This bug also happens in 1.16 pre4

**Comment by zabi94** [comment]
I added the easy tag without looking. This was updating hell. Anyways, should be fixed in 1.0.3, should be soon available on cf

**Comment by DoltenBolten** [comment]
Yeah, I thought that it was weird that it said “easy”.
