### ISSUE TITLE
Crashes When Jumping Into Learning Potion in Cauldron

### ISSUE THREAD

**Issue by ghost** [zabi94/ExtraAlchemy#79]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
Bug

---

#### Version of the mod or build number:
localextraalchemy-fabric-1.16-1.0.3.jar

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
Singleplayer

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
1.16.1

---

#### Description (or what were you doing when it crashed):
I jumped into a cauldron filled with the learning potion. I've posted a report on the cauldron modifying mod here: https://github.com/Crupette/fluidpotions/issues/1.

Edit: Looking through the effect command, I just realized longer reach is an immersive portal potion (why they have a potion, I don't know), but that means that this mod isn't registering potions properly and is not the fault of fluid potions.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
https://paste.ee/p/Y4Jxq

---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
The mod list is:
```
GameInfo-mod-1.5.2+1.16.jar
GreaterEye-Fabric_1.16-1.0.17.jar
Hwyla-fabric-1.16-1.9.22-74.jar
PresenceFootsteps-r26+1.16-rc1.jar
appleskin-mc1.16-fabric-1.0.11.jar
betterthanmending-1.1.1b.jar
carpet-extra-1.16-1.4.0.jar
cauldronoverhaul-1.5.0.jar
chat-up-1.0.0-1.16.jar
classy-creepers-1.0.0+1.15.2.jar
durabilityviewer-1.16-fabric0.13.1-1.7.1.jar
dynamic-fps-1.1.4.jar
expandedstorage-5.2.8+1.16.jar
fabric-api-0.13.1+build.370-1.16.jar
fabric-carpet-1.16-1.4.0+v200623.jar
fabric-language-kotlin-1.3.71+build.1.jar
fluidpotions-1.1.3.jar
get-updated-version
gubbins-1.0.2-1.16.1.jar
immersive-portals-0.12(forMc1.16.1withFabric).jar
localextraalchemy-fabric-1.16-1.0.3.jar
modmenu-1.12.2+build.16.jar
mousewheelie-1.4.16+mc1.16-rc1.jar
rgbblocks-2.1.2.jar
```
---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
https://pastebin.com/EaWqu8z6

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
Graal 11 (Java JVM) - OSX Catalina

---

#### Other information that you think might be useful:
It appears that the issue occurs for every potion except for long reach. I'm not sure which mod is at fault, but the fluid potions mod registers potions dynamically from the vanilla registry. However, the crash log suggests it is the fluid potions mod's fault. I am not sure if it is an issue with registering potions properly in the vanilla registry or if it's loading custom potions that's the issue. So, I've posted a report on both repos. https://github.com/Crupette/fluidpotions/issues/1

**Comment by zabi94** [comment]
The crash log has expired or has been deleted. Make sure to use pastebin to save it
