### ISSUE TITLE
Server crash with 3.0.4

### ISSUE THREAD

**Issue by Shadows-of-Fire** [zabi94/ExtraAlchemy#8]
https://gist.github.com/Shadows-of-Fire/64182810e202fb8d3080d37c1eae2bc0
You seem to be searching for client-only classes on dedicated servers.

**Comment by zabi94** [comment]
thanks, hotfix waiting for curseforge approval, should arrive in a couple minutes

**Comment by zabi94** [comment]
hotfix is online
