### ISSUE TITLE
Missing Texture Error

### ISSUE THREAD

**Issue by ghost** [zabi94/ExtraAlchemy#80]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>Bug

---

#### Version of the mod or build number:
>1.0.4 (Fabric)

---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>Single player

---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>1.16.1

---

#### Description (or what were you doing when it crashed):
>When starting up the game, the below error prints to the logs. The game does not crash.

---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
```
ERROR class_1059 Using missing texture, unable to load extraalchemy:textures/mob_effect/returning.png : java.io.FileNotFoundException: extraalchemy:textures/mob_effect/returning.png
 java.io.FileNotFoundException: extraalchemy:textures/mob_effect/returning.png
	at net.minecraft.class_3294.method_14486(class_3294.java:68)
	at net.minecraft.class_3304.method_14486(class_3304.java:64)
	at net.minecraft.class_1059.method_18160(class_1059.java:179)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
```
---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>None

---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>Defaults

---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Ubuntu 20.04
>Java is version 1.8.0_252, using 64-bit architecture.

**Comment by zabi94** [comment]
Yeah, that's expected, I didn't include effect art for instant effects as they are never rendered in game, and nobody is gonna see them anyways. I could probably have a dummy texture to silence the log just because
