### ISSUE TITLE
Game/Server Crash when I want to install the mod

### ISSUE THREAD

**Issue by YassaaaTU** [zabi94/ExtraAlchemy#81]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)
Crash
---

#### Version of the mod or build number:
>(*)
_extraalchemy-fabric-1.16.1-1.0.4.jar_ **AND** _extraalchemy-fabric-1.16.1-1.1.0.jar_
>Meaning I tried BOTH!
---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)
Single Player **AND** Multiplayer (I run a server as well and with the mod)
---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)
Minecraft Version: **_1.16.1_**
---

#### Description (or what were you doing when it crashed):
>(*)
I want to start the Game with this Mod Installed but it fails even when I try it alone
Without this mod everything works flawlessly in my custom modpack
---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)
[The Link to My **Pastebin** RAW _Crash Report_](https://pastebin.com/raw/WMqvtL5m)
---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)
The full **Mods List** is available in the crash report: 
[The Link to My **Pastebin** RAW _Crash Report_](https://pastebin.com/raw/WMqvtL5m)
---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)
The Config Has not been altered for the reason that it did not even work. So it is safe to say that the Config is the Default config file. (but if it is absolutely necessary then just tell me and I will generated again and post it because I already deleted it) 
---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)
**Running Windows 10 with:**

> java version "1.8.0_261"
> Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
> Java HotSpot(TM) Client VM (build 25.261-b12, mixed mode)

---

#### Other information that you think might be useful:
>(-)
**Maybe my laptop is incomputable with the mod?** 
_Here are my specifications:_

**Processor:** 
>Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~2304 Mhz
>In short: Intel Core i3 7th Gen. 

**Graphics Card:**
>Integrated Intel Graphics

**RAM:**
>8gb // 2 4gb ram sticks 

**Other Info:**
>OS Name: Microsoft Windows 10 Home
>OS Version: 10.0.19041 N/A Build 19041

**Comment by zabi94** [comment]
I just tried this with just my mod and fabric api and it works just fine. Some mod in the pack is messing with potion colors. It will take me some time to find out which one is it oof

**Comment by zabi94** [comment]
There's a thing you can do to help me speed things up immensly, if you feel like it. Run the game with the `-Dmixin.debug=true` VM option and attach all the files in `.mixin.out/audit/` in your environment after it crashes (the .mixin.out folder might be hidden)?
Otherwise I'll have to download mod by mod, making sure the version is the same, and it will probably take the whole afternoon

**Comment by HyburdzMC** [comment]
> There's a thing you can do to help me speed things up immensly, if you feel like it. Run the game with the `-Dmixin.debug=true` VM option and attach all the files in `.mixin.out/audit/` in your environment after it crashes (the .mixin.out folder might be hidden)
> Otherwise I'll have to download mod by mod, making sure the version is the same, and it will probably take the whole afternoon

**mixin_implementation_report.csv:**
`Class,Method,Signature,Interface`

**mixin_implementation_report.txt:**
`Mixin Implementation Report generated on 2020-08-04 00:21:12`

**Comment by zabi94** [comment]
Does this error happen without the mod Colormatic? They are changing the way potion color works, and it's their code that crash, not Extra Alchemy's
