### ISSUE TITLE
Brewing stand mixin ticking crash

### ISSUE THREAD

**Issue by tambry** [zabi94/ExtraAlchemy#82]
**Describe the bug**
Crash ticking brewing stand due to ExtraAlchemy's mixin.

**To Reproduce**
[Server download](https://mega.nz/file/ccRi2QKB#wrchDIL_byi6fcZFbtZ-Lzh63eHFo5_Q1WvQJcBziJs)  
The full server ready to start up.

Seems to be caused due to a combination of some other mods, but I unfortunately didn't have the time to narrow it down yet.

1. Use same mods on the client as the server has.
2. Set `extraPieces.enabled` to `false` in `config/Adorn.json5` on the client (unrelated bug https://github.com/Juuxel/Adorn/issues/96).
3. Launch the server.
4. Join the server `[::]:1337`.
5. `/tp 198 67.0 -335` (give yourself OP or such)
6. Wait a minute or two for the crash to occur. Or simply relog to trigger the necessary tick.

[latest.log](https://github.com/zabi94/ExtraAlchemy/files/5030890/latest.log)
[crash-2020-08-05_22.40.02-server.txt](https://github.com/zabi94/ExtraAlchemy/files/5030892/crash-2020-08-05_22.40.02-server.txt)

**Environment (please complete the following information):**
 - Mod Version: 1.2.0
 - MC Version: 1.16.1
 - Fabric Version: 0.6.1.45
 - Fabric API version: Fabric API 0.16.2 build 385
 - System: Windows 10 19041.388
 - Installation type: Server

**Comment by zabi94** [comment]
Fix available on cf when approved (should take a couple minutes at most)
