### ISSUE TITLE
In 1.16.1, the potion bag gui cannot be opened in an online game, it works fine in single player.

### ISSUE THREAD

**Issue by rikka0w0** [zabi94/ExtraAlchemy#85]
As the title says. I'm hosting a Fabric modded server. The potion bag gui cannot be opened when I connect to the server, but it works in my single player game. However, my friend can use the item normally on the server.

I'm not sure if this is a bug of this mod, some other mods might be responsible for this.

**Comment by zabi94** [comment]
Please use the provided bug report form.The bag works fine with vanilla + mod.
I'm not asking for issues here on github because I like them better. I'm asking because they tell you what data I **need** to fix the problem

**Comment by rikka0w0** [comment]
It does not crash the game, so no crash report. When sneaking+right clicking the potion bag, nothing happens.

**Comment by zabi94** [comment]
That is a bug though. There is the option to report a bug

**Comment by rikka0w0** [comment]
Okay... I think I just found some clue.... Every time I attempt to open the potion bag Gui, the following pops up in the client log:
`Trying to open invalid screen with name: Potion Bag`. Looks like the client side Gui is not registered properly.

**Comment by zabi94** [comment]
Yes. I could have told you that. But you didn't include the logs, which were askeed for in the bug report form...

**Comment by zabi94** [comment]
#87 is a better report for this same issue btw. I'm locking this thread and moving there
