### ISSUE TITLE
[1.16.1] Empty Rings unobtainable?

### ISSUE THREAD

**Issue by LuminaSapphira** [zabi94/ExtraAlchemy#86]
**Describe the bug**
As far as I can tell based on an in-game search and scouring the source code, there doesn't seem to be a way to acquire Empty Rings to craft potion rings. Am I oblivious, or is this intentional, or is this actually a bug?

 - Extra Alchemy Config:
https://hastebin.com/uwesikewok.json

**Environment:**
 - Mod Version: 1.2.1
 - MC Version: 1.16.1
 - Fabric Version: 0.9.2+build.206
 - Fabric API version: 0.17.0+build.386-1.16.1
 - System: Arch Linux
 - Installation type: Single Player

**Comment by zabi94** [comment]
No, I forgot to include a vanilla recipe and people apparently never noticed or didn't bother to report. 
I'll fix this asap, for the time being you can include a recipe through the vanilla datapacks
