### ISSUE TITLE
Magnetism allows for Duplication Glitch on Multiplayer servers.

### ISSUE THREAD

**Issue by SpiderKolo** [zabi94/ExtraAlchemy#89]
**Describe the bug**
(Redacted), item will be duplicated.

**To Reproduce**
(Redacted)
3. ... that's really it.

**Expected behavior**
All players who can reach item and are under this potion effect will pick up said item and produce copy of it. Nearest player without the Magnetism who could pick the item will also get a copy of it.

**Screenshots**
Don't possess any screenshots of it, but description alone should be enough to explain how it works well enough... I hope...
(Redacted)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: Don't have access to that.
 - Mod List: https://pastebin.pl/view/003b0294
 - Extra Alchemy Config: Don't have access to that.

**Environment:**
 - Mod Version: 1.3.0
 - MC Version: 1.16.3
 - Fabric Version: 0.10.3+build211
 - Fabric API version: Fabric Api 0.24.1; build.412 1.16
 - System: Windows 10
 - Installation type: Dedicated Server (Tested), Lan (Not Tested), Singleplayer (Not Tested, but Carpet mod let's you spawn an instance of a player which can be controlled by commands and it's highly likely that it will also work. I didn't had Carpet in modpack when bug happened, but I suspect it working "well" with it)

**Additional context**
I found this glitch accidentally when (redacted). The guy who owns the server told me he did that because of corruption in world, but I'm not sure what kind of corruption and if that's the real reason...

**Comment by zabi94** [comment]
I'll fix asap

**Comment by SpiderKolo** [comment]
Oh, maybe next time I will not post exact instructions how to do that kind of glitch... like... publicly.
Thanks for fast response.

**Comment by zabi94** [comment]
Can you please check if the latest version (1.3.1) fixes the issue on your server?

**Comment by SpiderKolo** [comment]
I don't own the server.
I can let the owner know that there is new version of the mod, but he isn't online at the moment.

**Comment by SpiderKolo** [comment]
Well from what I understood from owner, he seems to think this issue is fixed.
We are testing this currently on 1.16.4 and it works fine.

Thanks for fixing this issue :D

**Comment by zabi94** [comment]
Awesome, thank you!
