### ISSUE TITLE
(Crash Report)(1.10.2)(extraalchemy-0.3.0.4)(java.lang.ArrayIndexOutOfBoundsException: -1)

### ISSUE THREAD

**Issue by Lightone** [zabi94/ExtraAlchemy#9]
try this and pick the potion result, the game crash and happy new year =D.

![2017-01-18_20 01 20](https://cloud.githubusercontent.com/assets/2113099/22089504/86362710-ddb9-11e6-9f84-f4c477ea6316.png)

[Crash Log Pastebin](http://pastebin.com/CRbuAujd)

<details>
  <summary>Click to expand Crash Report</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.2.8.4.jar)
  CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 18/01/17 08:01 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at zabi.minecraft.extraalchemy.recipes.crafting.StickyPotionRecipeHandler.func_77572_b(StickyPotionRecipeHandler.java:74)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1235)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:54)
	at net.minecraft.inventory.InventoryCrafting.func_70298_a(SourceFile:80)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:124)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:324)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at zabi.minecraft.extraalchemy.recipes.crafting.StickyPotionRecipeHandler.func_77572_b(StickyPotionRecipeHandler.java:74)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1235)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:54)
	at net.minecraft.inventory.InventoryCrafting.func_70298_a(SourceFile:80)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:124)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:324)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Guartinajo'/464, l='MpServer', x=288,36, y=65,00, z=278,08]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (278,64,258), Chunk: (at 6,4,2 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 285885 game time, 9942 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 83 total; [EntityItem['item.item.potion'/40193, l='MpServer', x=275,55, y=76,13, z=265,31], EntityItem['item.item.potion'/56327, l='MpServer', x=274,03, y=76,00, z=266,62], EntityItem['item.item.potion'/40970, l='MpServer', x=275,14, y=76,00, z=266,36], EntityPig['Pig'/268, l='MpServer', x=338,48, y=67,00, z=216,08], EntityVillager['Villager'/269, l='MpServer', x=350,51, y=67,00, z=217,64], EntityPig['Pig'/270, l='MpServer', x=343,27, y=67,00, z=234,50], EntityItem['item.item.splash_potion'/47122, l='MpServer', x=276,38, y=76,00, z=265,45], EntityItem['item.item.splash_potion'/48148, l='MpServer', x=276,43, y=76,00, z=265,72], EntityItem['item.item.splash_potion'/61206, l='MpServer', x=275,21, y=76,00, z=264,52], EntityItem['item.item.splash_potion'/56857, l='MpServer', x=274,32, y=76,00, z=265,87], EntityItem['item.item.potion'/57647, l='MpServer', x=276,92, y=76,00, z=266,54], EntityItem['item.item.potion'/60226, l='MpServer', x=276,02, y=76,00, z=264,61], EntityItem['item.tile.stonebrick'/2391, l='MpServer', x=286,75, y=43,00, z=248,13], EntityItem['item.item.potion'/55903, l='MpServer', x=276,10, y=76,13, z=266,12], EntityItem['item.item.potion'/58983, l='MpServer', x=275,31, y=76,00, z=264,55], EntityPig['Pig'/106, l='MpServer', x=240,23, y=63,00, z=322,20], EntityPig['Pig'/107, l='MpServer', x=232,69, y=63,00, z=304,52], EntityPig['Pig'/108, l='MpServer', x=225,81, y=63,00, z=317,25], EntityItem['item.tile.stonebrick'/4973, l='MpServer', x=285,13, y=43,00, z=248,59], EntityPig['Pig'/109, l='MpServer', x=228,24, y=63,00, z=324,73], EntityItem['item.tile.stone.granite'/4975, l='MpServer', x=287,75, y=43,00, z=250,79], EntityPig['Pig'/113, l='MpServer', x=225,49, y=64,00, z=337,29], EntityItem['item.item.lingering_potion'/46194, l='MpServer', x=274,53, y=76,00, z=265,66], EntityCow['Cow'/119, l='MpServer', x=243,19, y=63,00, z=315,57], EntityItem['item.tile.stonebrick'/1399, l='MpServer', x=287,88, y=43,00, z=250,13], EntityCow['Cow'/120, l='MpServer', x=248,61, y=63,00, z=331,15], EntityCow['Cow'/133, l='MpServer', x=251,64, y=63,00, z=329,21], EntityPig['Pig'/134, l='MpServer', x=264,64, y=63,00, z=306,72], EntityPig['Pig'/135, l='MpServer', x=263,82, y=63,00, z=312,25], EntityPig['Pig'/136, l='MpServer', x=258,74, y=63,00, z=305,39], EntityPig['Pig'/153, l='MpServer', x=286,25, y=44,00, z=249,53], EntitySquid['Squid'/97432, l='MpServer', x=243,40, y=58,41, z=228,60], EntitySquid['Squid'/97434, l='MpServer', x=244,03, y=58,97, z=224,91], EntityItem['item.item.potion'/42399, l='MpServer', x=274,75, y=76,00, z=266,47], EntityItem['item.tile.stone.diorite'/163, l='MpServer', x=285,59, y=47,00, z=248,72], EntityItem['item.item.egg'/11171, l='MpServer', x=305,46, y=64,00, z=325,12], EntityItem['item.tile.stonebrick'/170, l='MpServer', x=285,27, y=44,00, z=249,66], EntityItem['item.tile.stonebrick'/173, l='MpServer', x=286,44, y=43,00, z=249,13], EntityItem['item.tile.stone.granite'/178, l='MpServer', x=287,13, y=47,00, z=249,77], EntityItem['item.tile.stone.granite'/179, l='MpServer', x=286,98, y=52,00, z=249,92], EntityItem['item.tile.gravel'/180, l='MpServer', x=284,96, y=52,00, z=249,27], EntityItem['item.tile.stone.granite'/181, l='MpServer', x=287,88, y=47,00, z=249,27], EntityItem['item.tile.stone.granite'/182, l='MpServer', x=285,45, y=47,00, z=250,13], EntityItem['item.tile.gravel'/183, l='MpServer', x=285,22, y=44,00, z=249,29], EntityItem['item.tile.gravel'/184, l='MpServer', x=286,13, y=43,00, z=249,23], EntityItem['item.tile.stonebrick'/1720, l='MpServer', x=286,19, y=43,00, z=250,88], EntityItem['item.item.flint'/185, l='MpServer', x=285,13, y=47,00, z=250,39], EntityItem['item.item.splash_potion'/45241, l='MpServer', x=274,68, y=76,00, z=265,89], EntityItem['item.tile.gravel'/186, l='MpServer', x=285,13, y=47,00, z=250,88], EntityItem['item.tile.stonebrick'/1722, l='MpServer', x=287,88, y=44,00, z=248,88], EntityItem['item.tile.stone.granite'/187, l='MpServer', x=286,88, y=47,00, z=250,84], EntityItem['item.item.null'/73146, l='MpServer', x=276,85, y=76,00, z=265,76], EntityItem['item.item.flint'/188, l='MpServer', x=285,13, y=47,00, z=248,13], EntityItem['item.tile.gravel'/189, l='MpServer', x=286,91, y=47,00, z=249,80], EntityItem['item.tile.stone.granite'/191, l='MpServer', x=286,67, y=47,00, z=248,41], EntityItem['item.item.null'/73409, l='MpServer', x=275,02, y=76,00, z=264,88], EntityFancyItemFrame['Golden Item Frame'/193, l='MpServer', x=282,50, y=66,50, z=276,03], EntityItem['item.item.splash_potion'/63425, l='MpServer', x=275,86, y=76,00, z=264,68], EntityFancyItemFrame['Golden Item Frame'/194, l='MpServer', x=283,50, y=66,50, z=276,03], EntityFancyItemFrame['Golden Item Frame'/195, l='MpServer', x=283,50, y=67,50, z=276,03], EntityFancyItemFrame['Golden Item Frame'/196, l='MpServer', x=282,50, y=67,50, z=276,03], EntityFancyItemFrame['Golden Item Frame'/197, l='MpServer', x=282,50, y=68,50, z=276,03], EntityFancyItemFrame['Golden Item Frame'/198, l='MpServer', x=283,50, y=68,50, z=276,03], EntityPig['Pig'/199, l='MpServer', x=274,45, y=65,00, z=285,45], EntityChicken['Chicken'/200, l='MpServer', x=279,20, y=62,00, z=327,50], EntityItem['item.tile.stone.diorite'/457, l='MpServer', x=286,88, y=47,00, z=248,20], EntityItem['item.tile.stonebrick'/458, l='MpServer', x=287,45, y=47,00, z=249,88], EntityItem['item.tile.stone.diorite'/1482, l='MpServer', x=286,74, y=43,00, z=249,88], EntityItem['item.tile.stone.diorite'/460, l='MpServer', x=285,13, y=47,00, z=250,13], EntityItem['item.item.potion'/43469, l='MpServer', x=275,95, y=76,13, z=265,64], EntityItem['item.tile.stone.diorite'/462, l='MpServer', x=286,56, y=47,00, z=250,88], EntityPlayerSP['Guartinajo'/464, l='MpServer', x=288,36, y=65,00, z=278,08], EntityItem['item.item.null'/76246, l='MpServer', x=274,65, y=76,00, z=265,56], EntityPig['Pig'/217, l='MpServer', x=299,55, y=65,00, z=267,55], EntityPig['Pig'/218, l='MpServer', x=299,22, y=65,00, z=288,51], EntityPig['Pig'/219, l='MpServer', x=296,43, y=64,00, z=317,24], EntityItem['item.item.splash_potion'/62171, l='MpServer', x=274,96, y=76,00, z=264,88], EntityChicken['Chicken'/220, l='MpServer', x=289,43, y=63,00, z=333,21], EntityItem['item.item.null'/74716, l='MpServer', x=276,02, y=76,00, z=264,88], EntityChicken['Chicken'/221, l='MpServer', x=302,45, y=63,00, z=342,18], EntityChicken['Chicken'/240, l='MpServer', x=305,27, y=64,00, z=325,16], EntityItem['item.item.potion'/44530, l='MpServer', x=274,40, y=76,00, z=266,22], EntityItem['item.item.null'/75763, l='MpServer', x=275,69, y=76,13, z=265,31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 358957432 bytes (342 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	cmdcam{0.2} [CMDCam] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.8.4} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	BetterAchievements{0.3.0.30} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.30.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	excore{1.6.1} [EXCore] (Excore-1.6.1-1.10.2(1).jar) 
	UCHIJAAAA	extraalchemy{0.3.0.4-hotfix-release} [Extra Alchemy] (extraalchemy-0.3.0.4-hotfix-release.jar) 
	UCHIJAAAA	JEI{3.12.1.287} [Just Enough Items] (jei_1.10.2-3.12.1.287.jar) 
	UCHIJAAAA	FEI{1.0.15} [Forever Enough Items] (ForeverEnoughItems-1.0.15-1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.5.3.65} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.3.65.jar) 
	UCHIJAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	reccomplex{1.2.1} [Recurrent Complex] (RecurrentComplex-1.2.1.jar) 
	UCHIJAAAA	shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
	UCHIJAAAA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJAAAA	thutcore{3.2.3} [ThutCore] (thutcore-1.9.4-3.2.3.jar) 
	UCHIJAAAA	thuttech{3.0.9} [Thut's Tech] (thuttech-3.0.9.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.2.8.4.jar)
  
CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
</details>

**Comment by zabi94** [comment]
Thanks, I'll fix it for the next version

**Comment by zabi94** [comment]
Fixed in upcoming update
