### ISSUE TITLE
[1.12.2] Getting kicked from server when affected by combustion that is applied from a mob

### ISSUE THREAD

**Issue by CalaMariGold** [zabi94/ExtraAlchemy#90]
**Describe the bug**
Using Rebirth of the Mobs, we had a Fire Zombie affect the player with combustion whenever they hit the player. This caused the player to be kicked from the server with the following error. 

![image](https://user-images.githubusercontent.com/57605926/104975221-11174100-59c8-11eb-851c-264d52c7c275.png)

**To Reproduce**
1. Install RotM
2. Add `minecraft:zombie;extraalchemy:effect.combustion;100;2;5;100;mob` to Mob Offense
3. Get hit by zombie on a server. Only occurs on servers.

Full issue here:
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/578

All information such as mod version and configs can be found in our repo.

**Environment (please complete the following information):**
 - Mod Version: build11-0.5.4
 - MC Version: 1.12.2
 - System: Windows 10
 - Installation type: DedicatedServer

**Comment by zabi94** [comment]
I don't touch packets with the combustion effect, and this never happened before, so I assume another mod is messing with network stuff.
I see LLibrary in the stack trace. Does the bug still occur when llibrary is removed?
I won't be able to look at this for a long time otherwise.
