### ISSUE TITLE
Potion rings turn into uncraftable potion rings that do not work

### ISSUE THREAD

**Issue by Neptainium** [zabi94/ExtraAlchemy#91]
**Describe the bug**
When you craft any potion ring, the ring stays a potion ring for a second before becoming an unusable one

**To Reproduce**
1. craft ring
2. craft potion with it
3. put it in your invintory
4. converts to unusable ring

**Expected behavior**
Expected ring to stay a usable ring

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: 
 - Mod List: 
 - Extra Alchemy Config:

**Environment (please complete the following information):**
 - Mod Version: extraalchemy-forge-1.12-build11-0.5.4
 - MC Version: 1,12,2
 - System: Windows 10
 - Installation type: DedicatedServer

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
Why was this closed?
