### ISSUE TITLE
Vials not working

### ISSUE THREAD

**Issue by Chilrona** [zabi94/ExtraAlchemy#92]
**Describe the bug**
Vials are craft-able but not usable. Putting them in a crafting table with a regular potion results in nothing and right clicking with the vial in hand does not fill the vial with a potion from my inventory. When I obtain a filled vial via REI it functions normally.

**To Reproduce**
1. Obtain a vial in-game
2. try to craft it with a potion or right-click with a potion in the inventory. I also tried it making sure no blocks were selected, e.g. looking at the sky.

**Expected behavior**
According to the mod page, I should be able to fill the vials with other potions.

**Screenshots**
![vialsbug](https://user-images.githubusercontent.com/79426196/108642356-f4a47380-7461-11eb-87e9-83bf3c5b260d.PNG)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - Mod List: https://docs.google.com/spreadsheets/d/1_jDZ2RXwEFVMux5BkN0m4Q4WuGbw0UGj20vWjc1rcJU/edit?usp=sharing
 - Extra Alchemy Config: all config options are set to true

**Environment (please complete the following information):**
 - Mod Version: 1.3.1
 - MC Version: 1.16.5
 - Fabric Version: 0.6.1.51
 - Fabric API version: 0.30.3
 - System: Windows 10
 - Installation type: Tried it using singleplayer and dedicated server

**Additional context**
I checked through my mods list and it doesn't look like anything should conflict. It's just a custom Vanilla+ mod pack. I also checked for required dependencies and I have cloth config, no more glowing pots, and fabric API.

**Comment by zabi94** [comment]
You need splash potions to fill vials, the tooltip on the empty one should tell you
