### ISSUE TITLE
[Suggestion] More configurable vials

### ISSUE THREAD

**Issue by IdrisQe** [zabi94/ExtraAlchemy#95]
(Apologies for the "bug" label, I didn't notice the practically-fine-print option for a "blank issue" that didn't follow a bug-report template)

I really like the idea of vials being a quick-to-use potion that's stackable, however I often find myself using ExtraAlchemy alongside mods that already make normal potions stackable, and the slightly faster use alone just doesn't feel like it's worth it to bother crafting them... I know this is more a modpack issue over an Extra Alchemy issue, but I see lots of potential for this.

So I was thinking, it'd be really neat if there were some more options to make Vials more distinct from normal potions... This is probably outside the scope of the mod, I have some ideas of some config options that could let Vials be more interesting in cases where players already have stackable potions:

1. Situational Dual-Use Vials: Changing Vials to be a sort of easier-to-aquire mini splash potion, crafted with normal potions instead of splash potions. Shift-R-Click does the current vial ability, breaking it and imbuing yourself, while normal right-clicking throws them like a Splash Potion, but without the added gunpowder, instead of splashing, it only affects the single entity it hits directly. This would let you use them to say, heal an ally or yourself at a moment's notice without splashing the effect to the mobs you're fighting, and without taking up two slots for splash and normal potions (or just throwing a normal splash potion at your feet less effectively). This is quite fitting too since it keeps their use as "fragile" items that break easily for their effects, and also makes them feel more streamlined for fast-paced combat scenarios.
2. Partitioned Vials: Changing Vials (and their recipe) so that you craft 4 of them with a single potion, but reducing the duration of any effects applied by them 8x. This would let you use them for buffs you only need briefly, without wasting a whole potion every time, perhaps stacking up to 32, basically letting you pick and choose when to use your potion effects with more granularity, as well as ration some of those harder-to-get effects (Ghast Tears are suffering to farm...) This is also quite fitting since vials are smaller than potions.
3. Arrow Tipping: Allowing you to hold a stack of Vials in your offhand while using a Bow or Crossbow to tip any normal arrows you fire with the potion effect. After all, let's be honest, the cost of making Tipped Arrows the normal way is ridiculous. You need to have beaten the Ender Dragon to even start since you need Dragon's Breath, a hard-to-renew resource. And most effects are pointless to put on an arrow anyway (even Harming since if your Bow does more than 12 damage it doesn't even add any extra damage) and the few that are, are more effective as splash potions anyway.

**Comment by zabi94** [comment]
With minecraft exploring the option of making potions stackable in their combat version snapshots, vials will probably be completely removed eventually. Your suggestions are nice, but I don't think they are enough to justify a whole item, it would just be redundant at that point.

As for the difficulty of crafting arrows, I'm planning a standalone mod to just make them craftable through a standard potion.

**Comment by IdrisQe** [comment]
Aw, that's a shame, I really like the vials. Granted I guess there's nothing stopping another mod from re-adding them in the future... But you're right, the latest combat snapshots really do make them rather redundant especially given the faster potion drinking.

Nice to know the arrows are getting some love! They (and Lingering Potions for that matter) feel like they've been horribly neglected by Mojang since their implementation.

**Comment by zabi94** [comment]
Yeah, they really are. I also have a commissioned mod coming up that gives potion related mechanics some love 😄

**Comment by IdrisQe** [comment]
I look forward to it! Alchemy has always had a ton of potential in Minecraft that was sorely squandered with their implementation of... just about everything regarding it.
